import type { SkillRecord } from '@/lib/db/skills'

const SNAPSHOT_DATE = '2026-06-01T00:00:00.000Z'

function snapshotSkill(input: {
  slug: string
  name: string
  description: string
  repo: string
  category: string
  tags: string[]
  frameworks: string[]
  stars: number
  quality: number
  license?: string
}): SkillRecord {
  return {
    id: `snapshot-${input.slug}`,
    slug: input.slug,
    name: input.name,
    description: input.description,
    long_description: input.description,
    tagline: input.description,
    author_name: input.repo.split('/')[0],
    author_email: null,
    author_url: `https://github.com/${input.repo.split('/')[0]}`,
    repository: `https://github.com/${input.repo}`,
    github_repo: input.repo,
    github_stars: input.stars,
    github_forks: 0,
    category: input.category,
    tags: input.tags,
    frameworks: input.frameworks,
    version: '1.0.0',
    license: input.license || 'Unknown',
    install_command: `npx skills add ${input.repo}`,
    npm_package: null,
    verified: false,
    submission_source: 'curated_snapshot',
    submitted_by_agent: null,
    ai_review_score: null,
    ai_review_approved: true,
    ai_review_issues: [],
    ai_review_suggestions: [],
    downloads: Math.max(1000, Math.round(input.stars * 1.2)),
    used_by: 0,
    rating: 0,
    review_count: 0,
    quality_score: input.quality,
    quality_signals: null,
    github_language: null,
    github_last_pushed_at: SNAPSHOT_DATE,
    created_at: SNAPSHOT_DATE,
    updated_at: SNAPSHOT_DATE,
  }
}

export const CURATED_SKILL_SNAPSHOT: SkillRecord[] = [
  snapshotSkill({
    slug: 'crawl4ai',
    name: 'Crawl4AI',
    description: 'Open-source LLM-friendly web crawler and scraper for agent workflows.',
    repo: 'unclecode/crawl4ai',
    category: 'Web Scraping',
    tags: ['web scraping', 'crawler', 'research', 'markdown'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 66_000,
    quality: 96,
    license: 'Apache-2.0',
  }),
  snapshotSkill({
    slug: 'firecrawl',
    name: 'Firecrawl',
    description: 'Turn websites into clean markdown or structured data for retrieval and agents.',
    repo: 'mendableai/firecrawl',
    category: 'Web Scraping',
    tags: ['crawler', 'markdown', 'rag', 'extract'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 34_000,
    quality: 94,
    license: 'AGPL-3.0',
  }),
  snapshotSkill({
    slug: 'n8n',
    name: 'n8n',
    description: 'Workflow automation for connecting agents to repeated operational tasks.',
    repo: 'n8n-io/n8n',
    category: 'Workflow Automation',
    tags: ['automation', 'workflow', 'integration', 'operations'],
    frameworks: ['API', 'CLI', 'Agent workflow'],
    stars: 190_000,
    quality: 92,
  }),
  snapshotSkill({
    slug: 'markitdown',
    name: 'MarkItDown',
    description: 'Convert PDFs, Office documents, and web files into clean markdown for agents.',
    repo: 'microsoft/markitdown',
    category: 'Document Processing',
    tags: ['pdf', 'markdown', 'documents', 'table extraction'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 80_000,
    quality: 93,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'llamaindex',
    name: 'LlamaIndex',
    description: 'Data framework for building RAG and knowledge workflows around agent tasks.',
    repo: 'run-llama/llama_index',
    category: 'RAG',
    tags: ['rag', 'knowledge', 'retrieval', 'document'],
    frameworks: ['Python', 'Codex', 'Claude Code'],
    stars: 42_000,
    quality: 91,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'openbb',
    name: 'OpenBB',
    description: 'Open-source investment research platform for financial analysis agents.',
    repo: 'OpenBB-finance/OpenBB',
    category: 'Finance',
    tags: ['finance', 'stocks', 'research', 'market data', 'filings'],
    frameworks: ['Python', 'Codex', 'Claude Code'],
    stars: 46_000,
    quality: 90,
  }),
  snapshotSkill({
    slug: 'vectorbt',
    name: 'Vectorbt',
    description: 'Fast quantitative research and backtesting workflows for financial agents.',
    repo: 'polakowo/vectorbt',
    category: 'Finance',
    tags: ['quant', 'backtesting', 'finance', 'portfolio'],
    frameworks: ['Python', 'Codex'],
    stars: 5_400,
    quality: 83,
  }),
  snapshotSkill({
    slug: 'serenity-skill',
    name: 'Serenity Skill',
    description: 'Stock analysis skill for market research and financial reasoning workflows.',
    repo: 'muxuuu/serenity-skill',
    category: 'Finance',
    tags: ['stocks', 'finance', 'analysis', 'stock research'],
    frameworks: ['Codex', 'Claude Code'],
    stars: 12_000,
    quality: 86,
  }),
  snapshotSkill({
    slug: 'last30days-skill',
    name: 'Last30days Skill',
    description: 'Research recent cross-source changes across Reddit, X, YouTube, Hacker News, and the web.',
    repo: 'mvanhorn/last30days-skill',
    category: 'Research',
    tags: ['research', 'recent events', 'news', 'briefing'],
    frameworks: ['Codex', 'Claude Code'],
    stars: 42_500,
    quality: 88,
  }),
  snapshotSkill({
    slug: 'addyosmani-agent-skills',
    name: 'Agent Skills',
    description: 'Production-grade engineering skills and quality gates for AI coding agents.',
    repo: 'addyosmani/agent-skills',
    category: 'Coding Agents',
    tags: ['agent-skills', 'coding-agents', 'claude-code', 'cursor', 'gemini-cli', 'engineering'],
    frameworks: ['Claude Code', 'Cursor', 'Gemini CLI', 'Codex'],
    stars: 61_800,
    quality: 94,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'seedance-2-0',
    name: 'Seedance 2.0 Skill',
    description: 'Creative video generation workflow skill for Seedance 2.0 filmmaking agents.',
    repo: 'Emily2040/seedance-2.0',
    category: 'Design',
    tags: ['video', 'creative', 'seedance', 'filmmaking'],
    frameworks: ['Codex', 'Claude Code'],
    stars: 8_000,
    quality: 84,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'playwright',
    name: 'Playwright',
    description: 'Reliable browser automation and testing engine for web agent tasks.',
    repo: 'microsoft/playwright',
    category: 'Browser Automation',
    tags: ['browser', 'testing', 'automation', 'e2e'],
    frameworks: ['Node.js', 'Python', 'Codex'],
    stars: 76_000,
    quality: 89,
    license: 'Apache-2.0',
  }),
  snapshotSkill({
    slug: 'browser-use',
    name: 'Browser Use',
    description: 'Browser automation layer for agents that need to interact with websites.',
    repo: 'browser-use/browser-use',
    category: 'Browser Automation',
    tags: ['browser', 'automation', 'agent'],
    frameworks: ['Python', 'Browser', 'Agent workflow'],
    stars: 75_000,
    quality: 90,
  }),
  snapshotSkill({
    slug: 'statsbomb-open-data',
    name: 'StatsBomb Open Data',
    description: 'Open football event data for match analysis, xG research, scouting, and World Cup-style dashboards.',
    repo: 'statsbomb/open-data',
    category: 'Sports Analytics',
    tags: ['football', 'soccer', 'world cup', 'xg', 'match data', 'sports'],
    frameworks: ['Python', 'Codex', 'Claude Code'],
    stars: 3_900,
    quality: 82,
  }),
  snapshotSkill({
    slug: 'mplsoccer',
    name: 'mplsoccer',
    description: 'Football pitch plotting and soccer analytics visuals for match reports and dashboards.',
    repo: 'andrewRowlinson/mplsoccer',
    category: 'Sports Analytics',
    tags: ['football', 'soccer', 'analytics', 'visualization', 'xg'],
    frameworks: ['Python', 'Codex'],
    stars: 1_100,
    quality: 78,
  }),
  snapshotSkill({
    slug: 'github',
    name: 'GitHub',
    description: 'Repository analysis, pull request review, issue triage, and release workflow automation.',
    repo: 'github/docs',
    category: 'Coding Agents',
    tags: ['github', 'pull request', 'review', 'repository', 'code'],
    frameworks: ['Codex', 'Cursor', 'Claude Code'],
    stars: 18_000,
    quality: 84,
  }),
]
