import type { SkillRecord } from '@/lib/db/skills'

const SNAPSHOT_DATE = '2026-06-01T00:00:00.000Z'

function snapshotSkill(input: {
  slug: string
  name: string
  description: string
  repo: string
  category: string
  tags: string[]
  frameworks: string[]
  stars: number
  quality: number
  forks?: number
  license?: string
  lastPushedAt?: string
  language?: string
  repository?: string
  installCommand?: string
  verified?: boolean
  longDescription?: string
  reviewScore?: number
  reviewIssues?: string[]
  reviewSuggestions?: string[]
}): SkillRecord {
  return {
    id: `snapshot-${input.slug}`,
    slug: input.slug,
    name: input.name,
    description: input.description,
    long_description: input.longDescription || input.description,
    tagline: input.description,
    author_name: input.repo.split('/')[0],
    author_email: null,
    author_url: `https://github.com/${input.repo.split('/')[0]}`,
    repository: input.repository || `https://github.com/${input.repo}`,
    github_repo: input.repo,
    github_stars: input.stars,
    github_forks: input.forks || 0,
    category: input.category,
    tags: input.tags,
    frameworks: input.frameworks,
    version: '1.0.0',
    license: input.license || 'Unknown',
    install_command: input.installCommand || `npx skills add ${input.repo}`,
    npm_package: null,
    verified: input.verified || false,
    submission_source: 'curated_snapshot',
    submitted_by_agent: null,
    ai_review_score: input.reviewScore
      ? { total: input.reviewScore, source: 'source-verified-skill-path' }
      : null,
    ai_review_approved: true,
    ai_review_issues: input.reviewIssues || [],
    ai_review_suggestions: input.reviewSuggestions || [],
    downloads: Math.max(1000, Math.round(input.stars * 1.2)),
    used_by: 0,
    rating: 0,
    review_count: 0,
    quality_score: input.quality,
    quality_signals: null,
    github_language: input.language || null,
    github_last_pushed_at: input.lastPushedAt || SNAPSHOT_DATE,
    created_at: SNAPSHOT_DATE,
    updated_at: SNAPSHOT_DATE,
  }
}

export const CURATED_SKILL_SNAPSHOT: SkillRecord[] = [
  snapshotSkill({
    slug: 'crawl4ai',
    name: 'Crawl4AI',
    description: 'Open-source LLM-friendly web crawler and scraper for agent workflows.',
    repo: 'unclecode/crawl4ai',
    category: 'Web Scraping',
    tags: ['web scraping', 'crawler', 'research', 'markdown'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 66_000,
    quality: 96,
    license: 'Apache-2.0',
  }),
  snapshotSkill({
    slug: 'firecrawl',
    name: 'Firecrawl',
    description: 'Turn websites into clean markdown or structured data for retrieval and agents.',
    repo: 'mendableai/firecrawl',
    category: 'Web Scraping',
    tags: ['crawler', 'markdown', 'rag', 'extract'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 34_000,
    quality: 94,
    license: 'AGPL-3.0',
  }),
  snapshotSkill({
    slug: 'n8n',
    name: 'n8n',
    description: 'Workflow automation for connecting agents to repeated operational tasks.',
    repo: 'n8n-io/n8n',
    category: 'Workflow Automation',
    tags: ['automation', 'workflow', 'integration', 'operations'],
    frameworks: ['API', 'CLI', 'Agent workflow'],
    stars: 190_000,
    quality: 92,
  }),
  snapshotSkill({
    slug: 'markitdown',
    name: 'MarkItDown',
    description: 'Convert PDFs, Office documents, and web files into clean markdown for agents.',
    repo: 'microsoft/markitdown',
    category: 'Document Processing',
    tags: ['pdf', 'markdown', 'documents', 'table extraction'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 80_000,
    quality: 93,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'llamaindex',
    name: 'LlamaIndex',
    description: 'Data framework for building RAG and knowledge workflows around agent tasks.',
    repo: 'run-llama/llama_index',
    category: 'RAG',
    tags: ['rag', 'knowledge', 'retrieval', 'document'],
    frameworks: ['Python', 'Codex', 'Claude Code'],
    stars: 42_000,
    quality: 91,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'openbb',
    name: 'OpenBB',
    description: 'Open-source investment research platform for financial analysis agents.',
    repo: 'OpenBB-finance/OpenBB',
    category: 'Finance',
    tags: ['finance', 'stocks', 'research', 'market data', 'filings'],
    frameworks: ['Python', 'Codex', 'Claude Code'],
    stars: 46_000,
    quality: 90,
  }),
  snapshotSkill({
    slug: 'vectorbt',
    name: 'Vectorbt',
    description: 'Fast quantitative research and backtesting workflows for financial agents.',
    repo: 'polakowo/vectorbt',
    category: 'Finance',
    tags: ['quant', 'backtesting', 'finance', 'portfolio'],
    frameworks: ['Python', 'Codex'],
    stars: 5_400,
    quality: 83,
  }),
  snapshotSkill({
    slug: 'serenity-skill',
    name: 'Serenity Skill',
    description: 'Stock analysis skill for market research and financial reasoning workflows.',
    repo: 'muxuuu/serenity-skill',
    category: 'Finance',
    tags: ['stocks', 'finance', 'analysis', 'stock research'],
    frameworks: ['Codex', 'Claude Code'],
    stars: 12_000,
    quality: 86,
  }),
  snapshotSkill({
    slug: 'last30days-skill',
    name: 'Last30days Skill',
    description: 'Research recent cross-source changes across Reddit, X, YouTube, Hacker News, and the web.',
    repo: 'mvanhorn/last30days-skill',
    category: 'Research',
    tags: ['research', 'recent events', 'news', 'briefing'],
    frameworks: ['Codex', 'Claude Code'],
    stars: 42_500,
    quality: 88,
  }),
  snapshotSkill({
    slug: 'addyosmani-agent-skills',
    name: 'Agent Skills',
    description: 'Production-grade engineering skills and quality gates for AI coding agents.',
    repo: 'addyosmani/agent-skills',
    category: 'Coding Agents',
    tags: ['agent-skills', 'coding-agents', 'claude-code', 'cursor', 'gemini-cli', 'engineering'],
    frameworks: ['Claude Code', 'Cursor', 'Gemini CLI', 'Codex'],
    stars: 61_800,
    quality: 94,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'davidondrej-skills',
    name: 'David Ondrej Skills',
    description:
      'Official Agent Skills for coding agents, research, workflow orchestration, docs, ops, and skill authoring.',
    repo: 'davidondrej/skills',
    category: 'Agent Skills',
    tags: [
      'agent-skills',
      'coding-agents',
      'research-agents',
      'workflow-agents',
      'agent-orchestration',
      'skill-authoring',
      'docs',
      'ops',
    ],
    frameworks: ['Codex', 'Claude Code', 'Cursor', 'Agent Workflows'],
    stars: 968,
    quality: 92,
    license: 'MIT',
    lastPushedAt: '2026-07-05T21:16:23.000Z',
  }),
  snapshotSkill({
    slug: 'aaron-he-zhu-aaron-marketing-skills',
    name: 'Aaron Marketing Skills',
    description: '120 marketing skills for SEO/GEO, influencer, paid ads, email, launch, organic social, and brand narrative agents.',
    repo: 'aaron-he-zhu/aaron-marketing-skills',
    category: 'Marketing',
    tags: ['marketing', 'seo', 'geo', 'influencer marketing', 'paid ads', 'email marketing', 'product launch', 'organic social', 'brand narrative', 'agent-skills'],
    frameworks: ['Claude Code', 'Codex', 'Marketing Agents'],
    stars: 2_313,
    quality: 90,
    license: 'Apache-2.0',
  }),
  snapshotSkill({
    slug: 'seedance-2-0',
    name: 'Seedance 2.0 Skill',
    description: 'Creative video generation workflow skill for Seedance 2.0 filmmaking agents.',
    repo: 'Emily2040/seedance-2.0',
    category: 'Design',
    tags: ['video', 'creative', 'seedance', 'filmmaking'],
    frameworks: ['Codex', 'Claude Code'],
    stars: 8_000,
    quality: 84,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'vox-director',
    name: 'Vox Director',
    description: 'Turn one topic into a narrated Vox-style paper-collage explainer or ad video, from script through captions.',
    longDescription:
      'A source-verified video-production skill that turns a topic, talking-head video, or product photo into a paper-collage explainer or short ad. It plans the script, keyframes, motion, voice-over, music, and captions. It uses external video and media providers plus local ffmpeg, so review provider costs, source rights, generated-media policy, and the final output before publishing.',
    repo: 'Alisa0808/vox-director',
    repository: 'https://github.com/Alisa0808/vox-director/tree/main',
    installCommand: 'npx skills add Alisa0808/vox-director --skill vox-director',
    category: 'design-creative',
    tags: ['agent-skill', 'video', 'video-generation', 'b-roll', 'vox-style', 'collage', 'explainer-video', 'motion-graphics', 'captions'],
    frameworks: ['Claude Code', 'Codex', 'Cursor', 'ffmpeg'],
    stars: 326,
    forks: 44,
    language: 'Python',
    quality: 88,
    reviewScore: 85,
    verified: true,
    license: 'MIT',
    lastPushedAt: '2026-07-17T09:03:22.000Z',
    reviewIssues: [
      'Uses external video and media providers; review provider cost, account, and content policies before running.',
      'Generated or sourced media still needs a human rights and brand-safety review before publication.',
    ],
    reviewSuggestions: [
      'Run one short test clip before committing to a larger rendering job.',
      'Use only approved source assets, voices, and brand material.',
    ],
  }),
  snapshotSkill({
    slug: 'seedance-prompt-en',
    name: 'Seedance 2.0 Prompt Writing',
    description: 'Write precise Seedance 2.0 prompts for multimodal video, camera movement, editing, music, and product storytelling.',
    longDescription:
      'A source-verified prompt-writing skill for Seedance 2.0 video generation. It structures text, image, video, and audio references into a clear production prompt with camera, timing, transition, and sound direction. It provides guidance rather than a provider-side install or rendering action; validate current Seedance capabilities and platform policies before generation.',
    repo: 'dexhunter/seedance2-skill',
    repository: 'https://github.com/dexhunter/seedance2-skill/tree/main',
    installCommand: 'npx skills add dexhunter/seedance2-skill --skill seedance-prompt-en',
    category: 'design-creative',
    tags: ['agent-skill', 'video', 'seedance', 'video-prompt', 'camera-movement', 'editing', 'multimodal', 'short-video'],
    frameworks: ['Claude Code', 'Codex', 'Cursor', 'Seedance 2.0'],
    stars: 2_917,
    forks: 288,
    quality: 91,
    reviewScore: 89,
    verified: true,
    license: 'MIT',
    lastPushedAt: '2026-02-18T13:00:03.000Z',
    reviewIssues: [
      'Model capabilities, asset limits, and platform rules can change; verify them before executing a production run.',
      'Do not use unapproved real-person imagery or source material that you do not have rights to use.',
    ],
    reviewSuggestions: [
      'Begin with a short low-cost clip to validate references, timing, and output quality.',
      'Keep the final prompt aligned with the platform content policy and the intended distribution channel.',
    ],
  }),
  snapshotSkill({
    slug: 'playwright',
    name: 'Playwright',
    description: 'Reliable browser automation and testing engine for web agent tasks.',
    repo: 'microsoft/playwright',
    category: 'Browser Automation',
    tags: ['browser', 'testing', 'automation', 'e2e'],
    frameworks: ['Node.js', 'Python', 'Codex'],
    stars: 76_000,
    quality: 89,
    license: 'Apache-2.0',
  }),
  snapshotSkill({
    slug: 'browser-use',
    name: 'Browser Use',
    description: 'Browser automation layer for agents that need to interact with websites.',
    repo: 'browser-use/browser-use',
    category: 'Browser Automation',
    tags: ['browser', 'automation', 'agent'],
    frameworks: ['Python', 'Browser', 'Agent workflow'],
    stars: 75_000,
    quality: 90,
  }),
  snapshotSkill({
    slug: 'statsbomb-open-data',
    name: 'StatsBomb Open Data',
    description: 'Open football event data for match analysis, xG research, scouting, and World Cup-style dashboards.',
    repo: 'statsbomb/open-data',
    category: 'Sports Analytics',
    tags: ['football', 'soccer', 'world cup', 'xg', 'match data', 'sports'],
    frameworks: ['Python', 'Codex', 'Claude Code'],
    stars: 3_900,
    quality: 82,
  }),
  snapshotSkill({
    slug: 'mplsoccer',
    name: 'mplsoccer',
    description: 'Football pitch plotting and soccer analytics visuals for match reports and dashboards.',
    repo: 'andrewRowlinson/mplsoccer',
    category: 'Sports Analytics',
    tags: ['football', 'soccer', 'analytics', 'visualization', 'xg'],
    frameworks: ['Python', 'Codex'],
    stars: 1_100,
    quality: 78,
  }),
  snapshotSkill({
    slug: 'github',
    name: 'GitHub',
    description: 'Repository analysis, pull request review, issue triage, and release workflow automation.',
    repo: 'github/docs',
    category: 'Coding Agents',
    tags: ['github', 'pull request', 'review', 'repository', 'code'],
    frameworks: ['Codex', 'Cursor', 'Claude Code'],
    stars: 18_000,
    quality: 84,
  }),
  snapshotSkill({
    slug: 'design-taste-frontend',
    name: 'Taste Skill: Anti-Slop Frontend',
    description: 'Design and implementation guidance for distinctive landing pages, portfolios, product demos, and purposeful redesigns.',
    longDescription:
      'A source-verified frontend skill that reads a product brief, chooses an intentional visual direction, and avoids generic template-like UI. Use it for landing pages, portfolios, product demos, and redesigns where visual taste, hierarchy, and implementation detail matter. It is not a substitute for a full product design system or domain-specific accessibility review.',
    repo: 'Leonxlnx/taste-skill',
    repository: 'https://github.com/Leonxlnx/taste-skill/tree/main/skills/taste-skill',
    installCommand: 'npx skills add Leonxlnx/taste-skill --skill design-taste-frontend',
    category: 'design-creative',
    tags: ['agent-skill', 'frontend', 'landing-page', 'product-demo', 'ui', 'design', 'design-taste'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 65_810,
    forks: 4_552,
    language: 'JavaScript',
    quality: 94,
    reviewScore: 92,
    verified: true,
    license: 'MIT',
    lastPushedAt: '2026-07-20T21:52:04.000Z',
  }),
  snapshotSkill({
    slug: 'anthropic-frontend-design',
    name: 'Frontend Design',
    description: 'Guidance for distinctive, intentional UI design, typography, visual direction, and non-template-like product interfaces.',
    longDescription:
      'A source-verified Anthropic skill for creating or reshaping interfaces with deliberate visual direction. Use it for new UI, visual redesigns, typography, composition, and product polish. Review the upstream source terms before redistributing or adopting it in production workflows.',
    repo: 'anthropics/skills',
    repository: 'https://github.com/anthropics/skills/tree/main/skills/frontend-design',
    installCommand: 'npx skills add anthropics/skills --skill frontend-design',
    category: 'design-creative',
    tags: ['agent-skill', 'frontend-design', 'ui', 'ux', 'typography', 'design-system', 'visual-direction'],
    frameworks: ['Claude Code', 'Codex', 'Cursor'],
    stars: 163_076,
    forks: 19_337,
    language: 'Python',
    quality: 93,
    reviewScore: 91,
    verified: true,
    license: 'Source terms (see LICENSE.txt)',
    lastPushedAt: '2026-07-17T02:47:40.000Z',
    reviewIssues: ['Use is subject to the upstream source terms; review LICENSE.txt before redistribution.'],
  }),
  snapshotSkill({
    slug: 'figma-implement-design',
    name: 'Figma Implement Design',
    description: 'Translate Figma designs into production-ready UI code with close visual fidelity and component-level detail.',
    longDescription:
      'A source-verified OpenAI skill for converting Figma specifications and links into production-ready application code. Use it when implementing components or screens against explicit Figma designs. Confirm access to the supplied design and review visual QA before treating a generated implementation as final.',
    repo: 'openai/skills',
    repository: 'https://github.com/openai/skills/tree/main/skills/.curated/figma-implement-design',
    installCommand: 'npx skills add openai/skills --skill figma-implement-design',
    category: 'design-creative',
    tags: ['agent-skill', 'figma', 'implementation', 'frontend', 'ui', 'component', 'visual-fidelity'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 24_000,
    forks: 1_628,
    language: 'Python',
    quality: 92,
    reviewScore: 90,
    verified: true,
    license: 'Source terms (see source)',
    lastPushedAt: '2026-07-14T16:47:46.000Z',
    reviewIssues: ['Requires access to the intended Figma design and a human visual QA pass.'],
  }),
  snapshotSkill({
    slug: 'vercel-web-design-guidelines',
    name: 'Web Design Guidelines',
    description: 'Review UI code for web interface guidelines, UX quality, accessibility, and interaction design best practices.',
    longDescription:
      'A source-verified Vercel skill for auditing UI code against web-interface guidelines. Use it for accessibility reviews, UX checks, design audits, and interaction-quality reviews. It evaluates implementation quality; it does not replace user research or formal accessibility certification.',
    repo: 'vercel-labs/agent-skills',
    repository: 'https://github.com/vercel-labs/agent-skills/tree/main/skills/web-design-guidelines',
    installCommand: 'npx skills add vercel-labs/agent-skills --skill web-design-guidelines',
    category: 'design-creative',
    tags: ['agent-skill', 'ui-review', 'ux', 'accessibility', 'web-design', 'design-audit', 'interaction'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 29_271,
    forks: 2_630,
    language: 'JavaScript',
    quality: 91,
    reviewScore: 89,
    verified: true,
    license: 'Source terms (see source)',
    lastPushedAt: '2026-07-20T22:42:51.000Z',
    reviewIssues: ['Use formal accessibility testing for regulated or high-compliance releases.'],
  }),
  snapshotSkill({
    slug: 'vercel-react-best-practices',
    name: 'Vercel React Best Practices',
    description: 'React and Next.js performance guidance for writing, reviewing, and refactoring production UI code.',
    longDescription:
      'A source-verified Vercel Engineering skill for React and Next.js performance work. Use it when building, reviewing, or refactoring components, pages, data fetching, bundle behavior, and rendering paths. Benchmark important user flows after changes instead of relying only on static guidance.',
    repo: 'vercel-labs/agent-skills',
    repository: 'https://github.com/vercel-labs/agent-skills/tree/main/skills/react-best-practices',
    installCommand: 'npx skills add vercel-labs/agent-skills --skill vercel-react-best-practices',
    category: 'coding-agents',
    tags: ['agent-skill', 'react', 'nextjs', 'performance', 'frontend', 'code-review', 'web-vitals'],
    frameworks: ['Codex', 'Claude Code', 'Cursor', 'React', 'Next.js'],
    stars: 29_271,
    forks: 2_630,
    language: 'JavaScript',
    quality: 93,
    reviewScore: 91,
    verified: true,
    license: 'MIT',
    lastPushedAt: '2026-07-20T22:42:51.000Z',
  }),
  snapshotSkill({
    slug: 'openai-playwright',
    name: 'Playwright Browser Skill',
    description: 'Automate a real browser from the terminal for navigation, form filling, snapshots, screenshots, extraction, and UI-flow debugging.',
    longDescription:
      'A source-verified OpenAI skill for real-browser tasks with Playwright. Use it for controlled navigation, form interaction, screenshots, data extraction, and UI-flow debugging. Do not use it to bypass platform protections or submit irreversible actions without an explicit review step.',
    repo: 'openai/skills',
    repository: 'https://github.com/openai/skills/tree/main/skills/.curated/playwright',
    installCommand: 'npx skills add openai/skills --skill playwright',
    category: 'browser-automation',
    tags: ['agent-skill', 'playwright', 'browser', 'testing', 'screenshots', 'automation', 'ui-debugging'],
    frameworks: ['Codex', 'Claude Code', 'Cursor', 'Playwright'],
    stars: 24_000,
    forks: 1_628,
    language: 'Python',
    quality: 91,
    reviewScore: 88,
    verified: true,
    license: 'Source terms (see source)',
    lastPushedAt: '2026-07-14T16:47:46.000Z',
    reviewIssues: ['Browser automation can submit data; confirm the target environment and review actions before execution.'],
  }),
  snapshotSkill({
    slug: 'anthropic-webapp-testing',
    name: 'Webapp Testing',
    description: 'Use Playwright to interact with and test local web applications, capture screenshots, debug UI behavior, and inspect browser logs.',
    longDescription:
      'A source-verified Anthropic skill for testing local web applications through Playwright. Use it for frontend functionality checks, browser-log inspection, screenshots, and regression testing. Keep test data non-sensitive and run against the intended local or sandbox environment.',
    repo: 'anthropics/skills',
    repository: 'https://github.com/anthropics/skills/tree/main/skills/webapp-testing',
    installCommand: 'npx skills add anthropics/skills --skill webapp-testing',
    category: 'browser-automation',
    tags: ['agent-skill', 'webapp-testing', 'playwright', 'browser', 'local-testing', 'regression', 'screenshots'],
    frameworks: ['Claude Code', 'Codex', 'Cursor', 'Playwright'],
    stars: 163_076,
    forks: 19_337,
    language: 'Python',
    quality: 93,
    reviewScore: 90,
    verified: true,
    license: 'Source terms (see LICENSE.txt)',
    lastPushedAt: '2026-07-17T02:47:40.000Z',
    reviewIssues: ['Use synthetic or approved test data; do not run destructive browser actions without review.'],
  }),
  snapshotSkill({
    slug: 'anthropic-canvas-design',
    name: 'Canvas Design',
    description: 'Create original visual art, posters, PNG assets, and PDF documents through a clear design philosophy.',
    longDescription:
      'A source-verified Anthropic skill for creating original static visual assets such as posters, images, and PDFs. Use it for new art direction and designed documents, not for copying the recognizable style of a living artist or reproducing copyrighted source work.',
    repo: 'anthropics/skills',
    repository: 'https://github.com/anthropics/skills/tree/main/skills/canvas-design',
    installCommand: 'npx skills add anthropics/skills --skill canvas-design',
    category: 'design-creative',
    tags: ['agent-skill', 'canvas', 'poster', 'visual-design', 'png', 'pdf', 'creative'],
    frameworks: ['Claude Code', 'Codex', 'Cursor'],
    stars: 163_076,
    forks: 19_337,
    language: 'Python',
    quality: 90,
    reviewScore: 87,
    verified: true,
    license: 'Source terms (see LICENSE.txt)',
    lastPushedAt: '2026-07-17T02:47:40.000Z',
    reviewIssues: ['Create original work; do not use it to imitate living artists or reproduce copyrighted source art.'],
  }),
  snapshotSkill({
    slug: 'anthropic-brand-guidelines',
    name: 'Anthropic Brand Guidelines',
    description: 'Apply Anthropic official brand colors, typography, and visual standards to appropriate Anthropic-related artifacts.',
    longDescription:
      'A source-verified Anthropic skill for applying Anthropic brand guidelines to relevant artifacts. Use it only when the work is authorized to use Anthropic visual identity. Do not reuse this source as generic branding guidance for unrelated organizations or products.',
    repo: 'anthropics/skills',
    repository: 'https://github.com/anthropics/skills/tree/main/skills/brand-guidelines',
    installCommand: 'npx skills add anthropics/skills --skill brand-guidelines',
    category: 'design-creative',
    tags: ['agent-skill', 'brand-guidelines', 'anthropic', 'typography', 'brand', 'visual-identity'],
    frameworks: ['Claude Code', 'Codex', 'Cursor'],
    stars: 163_076,
    forks: 19_337,
    language: 'Python',
    quality: 86,
    reviewScore: 83,
    verified: true,
    license: 'Source terms (see LICENSE.txt)',
    lastPushedAt: '2026-07-17T02:47:40.000Z',
    reviewIssues: ['Brand guidance is source-specific; do not apply Anthropic identity to unrelated organizations without permission.'],
  }),
  snapshotSkill({
    slug: 'vercel-deploy-to-vercel',
    name: 'Deploy to Vercel',
    description: 'Deploy applications and websites to Vercel, including preview deployments and shareable deployment links.',
    longDescription:
      'A source-verified Vercel skill for deploying applications and websites to Vercel. Use it for preview deployments, production delivery, and obtaining a shareable URL. Review the project, environment variables, domain settings, and deployment target before publishing externally.',
    repo: 'vercel-labs/agent-skills',
    repository: 'https://github.com/vercel-labs/agent-skills/tree/main/skills/deploy-to-vercel',
    installCommand: 'npx skills add vercel-labs/agent-skills --skill deploy-to-vercel',
    category: 'devops',
    tags: ['agent-skill', 'vercel', 'deploy', 'preview-deployment', 'deployment', 'hosting', 'vercel-deploy-claimable'],
    frameworks: ['Codex', 'Claude Code', 'Cursor', 'Vercel'],
    stars: 29_271,
    forks: 2_630,
    language: 'JavaScript',
    quality: 90,
    reviewScore: 88,
    verified: true,
    license: 'Source terms (see source)',
    lastPushedAt: '2026-07-20T22:42:51.000Z',
    reviewIssues: ['Deployment can publish external changes; review the target project and production settings before use.'],
  }),
]
