import type { SkillRecord } from '@/lib/db/skills'

const SNAPSHOT_DATE = '2026-06-01T00:00:00.000Z'

function snapshotSkill(input: {
  slug: string
  name: string
  description: string
  repo: string
  category: string
  tags: string[]
  frameworks: string[]
  stars: number
  quality: number
  forks?: number
  license?: string
  lastPushedAt?: string
  language?: string
  repository?: string
  installCommand?: string
  verified?: boolean
  longDescription?: string
  reviewScore?: number
  reviewIssues?: string[]
  reviewSuggestions?: string[]
}): SkillRecord {
  return {
    id: `snapshot-${input.slug}`,
    slug: input.slug,
    name: input.name,
    description: input.description,
    long_description: input.longDescription || input.description,
    tagline: input.description,
    author_name: input.repo.split('/')[0],
    author_email: null,
    author_url: `https://github.com/${input.repo.split('/')[0]}`,
    repository: input.repository || `https://github.com/${input.repo}`,
    github_repo: input.repo,
    github_stars: input.stars,
    github_forks: input.forks || 0,
    category: input.category,
    tags: input.tags,
    frameworks: input.frameworks,
    version: '1.0.0',
    license: input.license || 'Unknown',
    install_command: input.installCommand || `npx skills add ${input.repo}`,
    npm_package: null,
    verified: input.verified || false,
    submission_source: 'curated_snapshot',
    submitted_by_agent: null,
    ai_review_score: input.reviewScore
      ? { total: input.reviewScore, source: 'source-verified-skill-path' }
      : null,
    ai_review_approved: true,
    ai_review_issues: input.reviewIssues || [],
    ai_review_suggestions: input.reviewSuggestions || [],
    // A fallback record must never manufacture first-party adoption evidence.
    downloads: 0,
    used_by: 0,
    rating: 0,
    review_count: 0,
    quality_score: input.quality,
    quality_signals: null,
    github_language: input.language || null,
    github_last_pushed_at: input.lastPushedAt || SNAPSHOT_DATE,
    created_at: SNAPSHOT_DATE,
    updated_at: SNAPSHOT_DATE,
  }
}

export const CURATED_SKILL_SNAPSHOT: SkillRecord[] = [
  snapshotSkill({
    slug: 'crawl4ai',
    name: 'Crawl4AI',
    description: 'Open-source LLM-friendly web crawler and scraper for agent workflows.',
    repo: 'unclecode/crawl4ai',
    category: 'Web Scraping',
    tags: ['web scraping', 'crawler', 'research', 'markdown'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 66_000,
    quality: 96,
    license: 'Apache-2.0',
  }),
  snapshotSkill({
    slug: 'firecrawl',
    name: 'Firecrawl',
    description: 'Turn websites into clean markdown or structured data for retrieval and agents.',
    repo: 'mendableai/firecrawl',
    category: 'Web Scraping',
    tags: ['crawler', 'markdown', 'rag', 'extract'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 34_000,
    quality: 94,
    license: 'AGPL-3.0',
  }),
  snapshotSkill({
    slug: 'n8n',
    name: 'n8n',
    description: 'Workflow automation for connecting agents to repeated operational tasks.',
    repo: 'n8n-io/n8n',
    category: 'Workflow Automation',
    tags: ['automation', 'workflow', 'integration', 'operations'],
    frameworks: ['API', 'CLI', 'Agent workflow'],
    stars: 190_000,
    quality: 92,
  }),
  snapshotSkill({
    slug: 'markitdown',
    name: 'MarkItDown',
    description: 'Convert PDFs, Office documents, and web files into clean markdown for agents.',
    repo: 'microsoft/markitdown',
    category: 'Document Processing',
    tags: ['pdf', 'markdown', 'documents', 'table extraction'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 80_000,
    quality: 93,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'llamaindex',
    name: 'LlamaIndex',
    description: 'Data framework for building RAG and knowledge workflows around agent tasks.',
    repo: 'run-llama/llama_index',
    category: 'RAG',
    tags: ['rag', 'knowledge', 'retrieval', 'document'],
    frameworks: ['Python', 'Codex', 'Claude Code'],
    stars: 42_000,
    quality: 91,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'openbb',
    name: 'OpenBB',
    description: 'Open-source investment research platform for financial analysis agents.',
    repo: 'OpenBB-finance/OpenBB',
    category: 'Finance',
    tags: ['finance', 'stocks', 'research', 'market data', 'filings'],
    frameworks: ['Python', 'Codex', 'Claude Code'],
    stars: 46_000,
    quality: 90,
  }),
  snapshotSkill({
    slug: 'vectorbt',
    name: 'Vectorbt',
    description: 'Fast quantitative research and backtesting workflows for financial agents.',
    repo: 'polakowo/vectorbt',
    category: 'Finance',
    tags: ['quant', 'backtesting', 'finance', 'portfolio'],
    frameworks: ['Python', 'Codex'],
    stars: 5_400,
    quality: 83,
  }),
  snapshotSkill({
    slug: 'serenity-skill',
    name: 'Serenity Skill',
    description: 'Stock analysis skill for market research and financial reasoning workflows.',
    repo: 'muxuuu/serenity-skill',
    category: 'Finance',
    tags: ['stocks', 'finance', 'analysis', 'stock research'],
    frameworks: ['Codex', 'Claude Code'],
    stars: 12_000,
    quality: 86,
  }),
  snapshotSkill({
    slug: 'last30days-skill',
    name: 'Last30days Skill',
    description: 'Research recent cross-source changes across Reddit, X, YouTube, Hacker News, and the web.',
    repo: 'mvanhorn/last30days-skill',
    category: 'Research',
    tags: ['research', 'recent events', 'news', 'briefing'],
    frameworks: ['Codex', 'Claude Code'],
    stars: 42_500,
    quality: 88,
  }),
  snapshotSkill({
    slug: 'addyosmani-agent-skills',
    name: 'Agent Skills',
    description: 'Production-grade engineering skills and quality gates for AI coding agents.',
    repo: 'addyosmani/agent-skills',
    category: 'Coding Agents',
    tags: ['agent-skills', 'coding-agents', 'claude-code', 'cursor', 'gemini-cli', 'engineering'],
    frameworks: ['Claude Code', 'Cursor', 'Gemini CLI', 'Codex'],
    stars: 61_800,
    quality: 94,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'davidondrej-skills',
    name: 'David Ondrej Skills',
    description:
      'Official Agent Skills for coding agents, research, workflow orchestration, docs, ops, and skill authoring.',
    repo: 'davidondrej/skills',
    category: 'Agent Skills',
    tags: [
      'agent-skills',
      'coding-agents',
      'research-agents',
      'workflow-agents',
      'agent-orchestration',
      'skill-authoring',
      'docs',
      'ops',
    ],
    frameworks: ['Codex', 'Claude Code', 'Cursor', 'Agent Workflows'],
    stars: 968,
    quality: 92,
    license: 'MIT',
    lastPushedAt: '2026-07-05T21:16:23.000Z',
  }),
  snapshotSkill({
    slug: 'aaron-he-zhu-aaron-marketing-skills',
    name: 'Aaron Marketing Skills',
    description: '120 marketing skills for SEO/GEO, influencer, paid ads, email, launch, organic social, and brand narrative agents.',
    repo: 'aaron-he-zhu/aaron-marketing-skills',
    category: 'Marketing',
    tags: ['marketing', 'seo', 'geo', 'influencer marketing', 'paid ads', 'email marketing', 'product launch', 'organic social', 'brand narrative', 'agent-skills'],
    frameworks: ['Claude Code', 'Codex', 'Marketing Agents'],
    stars: 2_313,
    quality: 90,
    license: 'Apache-2.0',
  }),
  snapshotSkill({
    slug: 'seedance-2-0',
    name: 'Seedance 2.0 Skill',
    description: 'Creative video generation workflow skill for Seedance 2.0 filmmaking agents.',
    repo: 'Emily2040/seedance-2.0',
    category: 'Design',
    tags: ['video', 'creative', 'seedance', 'filmmaking'],
    frameworks: ['Codex', 'Claude Code'],
    stars: 8_000,
    quality: 84,
    license: 'MIT',
  }),
  snapshotSkill({
    slug: 'vox-director',
    name: 'Vox Director',
    description: 'Turn one topic into a narrated Vox-style paper-collage explainer or ad video, from script through captions.',
    longDescription:
      'A source-verified video-production skill that turns a topic, talking-head video, or product photo into a paper-collage explainer or short ad. It plans the script, keyframes, motion, voice-over, music, and captions. It uses external video and media providers plus local ffmpeg, so review provider costs, source rights, generated-media policy, and the final output before publishing.',
    repo: 'Alisa0808/vox-director',
    repository: 'https://github.com/Alisa0808/vox-director/tree/main',
    installCommand: 'npx skills add Alisa0808/vox-director --skill vox-director',
    category: 'design-creative',
    tags: ['agent-skill', 'video', 'video-generation', 'b-roll', 'vox-style', 'collage', 'explainer-video', 'motion-graphics', 'captions'],
    frameworks: ['Claude Code', 'Codex', 'Cursor', 'ffmpeg'],
    stars: 326,
    forks: 44,
    language: 'Python',
    quality: 88,
    reviewScore: 85,
    verified: true,
    license: 'MIT',
    lastPushedAt: '2026-07-17T09:03:22.000Z',
    reviewIssues: [
      'Uses external video and media providers; review provider cost, account, and content policies before running.',
      'Generated or sourced media still needs a human rights and brand-safety review before publication.',
    ],
    reviewSuggestions: [
      'Run one short test clip before committing to a larger rendering job.',
      'Use only approved source assets, voices, and brand material.',
    ],
  }),
  snapshotSkill({
    slug: 'seedance-prompt-en',
    name: 'Seedance 2.0 Prompt Writing',
    description: 'Write precise Seedance 2.0 prompts for multimodal video, camera movement, editing, music, and product storytelling.',
    longDescription:
      'A source-verified prompt-writing skill for Seedance 2.0 video generation. It structures text, image, video, and audio references into a clear production prompt with camera, timing, transition, and sound direction. It provides guidance rather than a provider-side install or rendering action; validate current Seedance capabilities and platform policies before generation.',
    repo: 'dexhunter/seedance2-skill',
    repository: 'https://github.com/dexhunter/seedance2-skill/tree/main',
    installCommand: 'npx skills add dexhunter/seedance2-skill --skill seedance-prompt-en',
    category: 'design-creative',
    tags: ['agent-skill', 'video', 'seedance', 'video-prompt', 'camera-movement', 'editing', 'multimodal', 'short-video'],
    frameworks: ['Claude Code', 'Codex', 'Cursor', 'Seedance 2.0'],
    stars: 2_917,
    forks: 288,
    quality: 91,
    reviewScore: 89,
    verified: true,
    license: 'MIT',
    lastPushedAt: '2026-02-18T13:00:03.000Z',
    reviewIssues: [
      'Model capabilities, asset limits, and platform rules can change; verify them before executing a production run.',
      'Do not use unapproved real-person imagery or source material that you do not have rights to use.',
    ],
    reviewSuggestions: [
      'Begin with a short low-cost clip to validate references, timing, and output quality.',
      'Keep the final prompt aligned with the platform content policy and the intended distribution channel.',
    ],
  }),
  snapshotSkill({
    slug: 'playwright',
    name: 'Playwright',
    description: 'Reliable browser automation and testing engine for web agent tasks.',
    repo: 'microsoft/playwright',
    category: 'Browser Automation',
    tags: ['browser', 'testing', 'automation', 'e2e'],
    frameworks: ['Node.js', 'Python', 'Codex'],
    stars: 76_000,
    quality: 89,
    license: 'Apache-2.0',
  }),
  snapshotSkill({
    slug: 'browser-use',
    name: 'Browser Use',
    description: 'Browser automation layer for agents that need to interact with websites.',
    repo: 'browser-use/browser-use',
    category: 'Browser Automation',
    tags: ['browser', 'automation', 'agent'],
    frameworks: ['Python', 'Browser', 'Agent workflow'],
    stars: 75_000,
    quality: 90,
  }),
  snapshotSkill({
    slug: 'statsbomb-open-data',
    name: 'StatsBomb Open Data',
    description: 'Open football event data for match analysis, xG research, scouting, and World Cup-style dashboards.',
    repo: 'statsbomb/open-data',
    category: 'Sports Analytics',
    tags: ['football', 'soccer', 'world cup', 'xg', 'match data', 'sports'],
    frameworks: ['Python', 'Codex', 'Claude Code'],
    stars: 3_900,
    quality: 82,
  }),
  snapshotSkill({
    slug: 'mplsoccer',
    name: 'mplsoccer',
    description: 'Football pitch plotting and soccer analytics visuals for match reports and dashboards.',
    repo: 'andrewRowlinson/mplsoccer',
    category: 'Sports Analytics',
    tags: ['football', 'soccer', 'analytics', 'visualization', 'xg'],
    frameworks: ['Python', 'Codex'],
    stars: 1_100,
    quality: 78,
  }),
  snapshotSkill({
    slug: 'github',
    name: 'GitHub',
    description: 'Repository analysis, pull request review, issue triage, and release workflow automation.',
    repo: 'github/docs',
    category: 'Coding Agents',
    tags: ['github', 'pull request', 'review', 'repository', 'code'],
    frameworks: ['Codex', 'Cursor', 'Claude Code'],
    stars: 18_000,
    quality: 84,
  }),
  snapshotSkill({
    slug: 'design-taste-frontend',
    name: 'Taste Skill: Anti-Slop Frontend',
    description: 'Design and implementation guidance for distinctive landing pages, portfolios, product demos, and purposeful redesigns.',
    longDescription:
      'A source-verified frontend skill that reads a product brief, chooses an intentional visual direction, and avoids generic template-like UI. Use it for landing pages, portfolios, product demos, and redesigns where visual taste, hierarchy, and implementation detail matter. It is not a substitute for a full product design system or domain-specific accessibility review.',
    repo: 'Leonxlnx/taste-skill',
    repository: 'https://github.com/Leonxlnx/taste-skill/tree/main/skills/taste-skill',
    installCommand: 'npx skills add Leonxlnx/taste-skill --skill design-taste-frontend',
    category: 'design-creative',
    tags: ['agent-skill', 'frontend', 'landing-page', 'product-demo', 'ui', 'design', 'design-taste'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 65_810,
    forks: 4_552,
    language: 'JavaScript',
    quality: 94,
    reviewScore: 92,
    verified: true,
    license: 'MIT',
    lastPushedAt: '2026-07-20T21:52:04.000Z',
  }),
  snapshotSkill({
    slug: 'anthropic-frontend-design',
    name: 'Frontend Design',
    description: 'Guidance for distinctive, intentional UI design, typography, visual direction, and non-template-like product interfaces.',
    longDescription:
      'A source-verified Anthropic skill for creating or reshaping interfaces with deliberate visual direction. Use it for new UI, visual redesigns, typography, composition, and product polish. Review the upstream source terms before redistributing or adopting it in production workflows.',
    repo: 'anthropics/skills',
    repository: 'https://github.com/anthropics/skills/tree/main/skills/frontend-design',
    installCommand: 'npx skills add anthropics/skills --skill frontend-design',
    category: 'design-creative',
    tags: ['agent-skill', 'frontend-design', 'ui', 'ux', 'typography', 'design-system', 'visual-direction'],
    frameworks: ['Claude Code', 'Codex', 'Cursor'],
    stars: 163_076,
    forks: 19_337,
    language: 'Python',
    quality: 93,
    reviewScore: 91,
    verified: true,
    license: 'Source terms (see LICENSE.txt)',
    lastPushedAt: '2026-07-17T02:47:40.000Z',
    reviewIssues: ['Use is subject to the upstream source terms; review LICENSE.txt before redistribution.'],
  }),
  snapshotSkill({
    slug: 'figma-implement-design',
    name: 'Figma Implement Design',
    description: 'Translate Figma designs into production-ready UI code with close visual fidelity and component-level detail.',
    longDescription:
      'A source-verified OpenAI skill for converting Figma specifications and links into production-ready application code. Use it when implementing components or screens against explicit Figma designs. Confirm access to the supplied design and review visual QA before treating a generated implementation as final.',
    repo: 'openai/skills',
    repository: 'https://github.com/openai/skills/tree/main/skills/.curated/figma-implement-design',
    installCommand: 'npx skills add openai/skills --skill figma-implement-design',
    category: 'design-creative',
    tags: ['agent-skill', 'figma', 'implementation', 'frontend', 'ui', 'component', 'visual-fidelity'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 24_000,
    forks: 1_628,
    language: 'Python',
    quality: 92,
    reviewScore: 90,
    verified: true,
    license: 'Source terms (see source)',
    lastPushedAt: '2026-07-14T16:47:46.000Z',
    reviewIssues: ['Requires access to the intended Figma design and a human visual QA pass.'],
  }),
  snapshotSkill({
    slug: 'vercel-web-design-guidelines',
    name: 'Web Design Guidelines',
    description: 'Review UI code for web interface guidelines, UX quality, accessibility, and interaction design best practices.',
    longDescription:
      'A source-verified Vercel skill for auditing UI code against web-interface guidelines. Use it for accessibility reviews, UX checks, design audits, and interaction-quality reviews. It evaluates implementation quality; it does not replace user research or formal accessibility certification.',
    repo: 'vercel-labs/agent-skills',
    repository: 'https://github.com/vercel-labs/agent-skills/tree/main/skills/web-design-guidelines',
    installCommand: 'npx skills add vercel-labs/agent-skills --skill web-design-guidelines',
    category: 'design-creative',
    tags: ['agent-skill', 'ui-review', 'ux', 'accessibility', 'web-design', 'design-audit', 'interaction'],
    frameworks: ['Codex', 'Claude Code', 'Cursor'],
    stars: 29_271,
    forks: 2_630,
    language: 'JavaScript',
    quality: 91,
    reviewScore: 89,
    verified: true,
    license: 'Source terms (see source)',
    lastPushedAt: '2026-07-20T22:42:51.000Z',
    reviewIssues: ['Use formal accessibility testing for regulated or high-compliance releases.'],
  }),
  snapshotSkill({
    slug: 'vercel-react-best-practices',
    name: 'Vercel React Best Practices',
    description: 'React and Next.js performance guidance for writing, reviewing, and refactoring production UI code.',
    longDescription:
      'A source-verified Vercel Engineering skill for React and Next.js performance work. Use it when building, reviewing, or refactoring components, pages, data fetching, bundle behavior, and rendering paths. Benchmark important user flows after changes instead of relying only on static guidance.',
    repo: 'vercel-labs/agent-skills',
    repository: 'https://github.com/vercel-labs/agent-skills/tree/main/skills/react-best-practices',
    installCommand: 'npx skills add vercel-labs/agent-skills --skill vercel-react-best-practices',
    category: 'coding-agents',
    tags: ['agent-skill', 'react', 'nextjs', 'performance', 'frontend', 'code-review', 'web-vitals'],
    frameworks: ['Codex', 'Claude Code', 'Cursor', 'React', 'Next.js'],
    stars: 29_271,
    forks: 2_630,
    language: 'JavaScript',
    quality: 93,
    reviewScore: 91,
    verified: true,
    license: 'MIT',
    lastPushedAt: '2026-07-20T22:42:51.000Z',
  }),
  snapshotSkill({
    slug: 'openai-playwright',
    name: 'Playwright Browser Skill',
    description: 'Automate a real browser from the terminal for navigation, form filling, snapshots, screenshots, extraction, and UI-flow debugging.',
    longDescription:
      'A source-verified OpenAI skill for real-browser tasks with Playwright. Use it for controlled navigation, form interaction, screenshots, data extraction, and UI-flow debugging. Do not use it to bypass platform protections or submit irreversible actions without an explicit review step.',
    repo: 'openai/skills',
    repository: 'https://github.com/openai/skills/tree/main/skills/.curated/playwright',
    installCommand: 'npx skills add openai/skills --skill playwright',
    category: 'browser-automation',
    tags: ['agent-skill', 'playwright', 'browser', 'testing', 'screenshots', 'automation', 'ui-debugging'],
    frameworks: ['Codex', 'Claude Code', 'Cursor', 'Playwright'],
    stars: 24_000,
    forks: 1_628,
    language: 'Python',
    quality: 91,
    reviewScore: 88,
    verified: true,
    license: 'Source terms (see source)',
    lastPushedAt: '2026-07-14T16:47:46.000Z',
    reviewIssues: ['Browser automation can submit data; confirm the target environment and review actions before execution.'],
  }),
  snapshotSkill({
    slug: 'anthropic-webapp-testing',
    name: 'Webapp Testing',
    description: 'Use Playwright to interact with and test local web applications, capture screenshots, debug UI behavior, and inspect browser logs.',
    longDescription:
      'A source-verified Anthropic skill for testing local web applications through Playwright. Use it for frontend functionality checks, browser-log inspection, screenshots, and regression testing. Keep test data non-sensitive and run against the intended local or sandbox environment.',
    repo: 'anthropics/skills',
    repository: 'https://github.com/anthropics/skills/tree/main/skills/webapp-testing',
    installCommand: 'npx skills add anthropics/skills --skill webapp-testing',
    category: 'browser-automation',
    tags: ['agent-skill', 'webapp-testing', 'playwright', 'browser', 'local-testing', 'regression', 'screenshots'],
    frameworks: ['Claude Code', 'Codex', 'Cursor', 'Playwright'],
    stars: 163_076,
    forks: 19_337,
    language: 'Python',
    quality: 93,
    reviewScore: 90,
    verified: true,
    license: 'Source terms (see LICENSE.txt)',
    lastPushedAt: '2026-07-17T02:47:40.000Z',
    reviewIssues: ['Use synthetic or approved test data; do not run destructive browser actions without review.'],
  }),
  snapshotSkill({
    slug: 'anthropic-canvas-design',
    name: 'Canvas Design',
    description: 'Create original visual art, posters, PNG assets, and PDF documents through a clear design philosophy.',
    longDescription:
      'A source-verified Anthropic skill for creating original static visual assets such as posters, images, and PDFs. Use it for new art direction and designed documents, not for copying the recognizable style of a living artist or reproducing copyrighted source work.',
    repo: 'anthropics/skills',
    repository: 'https://github.com/anthropics/skills/tree/main/skills/canvas-design',
    installCommand: 'npx skills add anthropics/skills --skill canvas-design',
    category: 'design-creative',
    tags: ['agent-skill', 'canvas', 'poster', 'visual-design', 'png', 'pdf', 'creative'],
    frameworks: ['Claude Code', 'Codex', 'Cursor'],
    stars: 163_076,
    forks: 19_337,
    language: 'Python',
    quality: 90,
    reviewScore: 87,
    verified: true,
    license: 'Source terms (see LICENSE.txt)',
    lastPushedAt: '2026-07-17T02:47:40.000Z',
    reviewIssues: ['Create original work; do not use it to imitate living artists or reproduce copyrighted source art.'],
  }),
  snapshotSkill({
    slug: 'anthropic-brand-guidelines',
    name: 'Anthropic Brand Guidelines',
    description: 'Apply Anthropic official brand colors, typography, and visual standards to appropriate Anthropic-related artifacts.',
    longDescription:
      'A source-verified Anthropic skill for applying Anthropic brand guidelines to relevant artifacts. Use it only when the work is authorized to use Anthropic visual identity. Do not reuse this source as generic branding guidance for unrelated organizations or products.',
    repo: 'anthropics/skills',
    repository: 'https://github.com/anthropics/skills/tree/main/skills/brand-guidelines',
    installCommand: 'npx skills add anthropics/skills --skill brand-guidelines',
    category: 'design-creative',
    tags: ['agent-skill', 'brand-guidelines', 'anthropic', 'typography', 'brand', 'visual-identity'],
    frameworks: ['Claude Code', 'Codex', 'Cursor'],
    stars: 163_076,
    forks: 19_337,
    language: 'Python',
    quality: 86,
    reviewScore: 83,
    verified: true,
    license: 'Source terms (see LICENSE.txt)',
    lastPushedAt: '2026-07-17T02:47:40.000Z',
    reviewIssues: ['Brand guidance is source-specific; do not apply Anthropic identity to unrelated organizations without permission.'],
  }),
  snapshotSkill({
    slug: 'vercel-deploy-to-vercel',
    name: 'Deploy to Vercel',
    description: 'Deploy applications and websites to Vercel, including preview deployments and shareable deployment links.',
    longDescription:
      'A source-verified Vercel skill for deploying applications and websites to Vercel. Use it for preview deployments, production delivery, and obtaining a shareable URL. Review the project, environment variables, domain settings, and deployment target before publishing externally.',
    repo: 'vercel-labs/agent-skills',
    repository: 'https://github.com/vercel-labs/agent-skills/tree/main/skills/deploy-to-vercel',
    installCommand: 'npx skills add vercel-labs/agent-skills --skill deploy-to-vercel',
    category: 'devops',
    tags: ['agent-skill', 'vercel', 'deploy', 'preview-deployment', 'deployment', 'hosting', 'vercel-deploy-claimable'],
    frameworks: ['Codex', 'Claude Code', 'Cursor', 'Vercel'],
    stars: 29_271,
    forks: 2_630,
    language: 'JavaScript',
    quality: 90,
    reviewScore: 88,
    verified: true,
    license: 'Source terms (see source)',
    lastPushedAt: '2026-07-20T22:42:51.000Z',
    reviewIssues: ['Deployment can publish external changes; review the target project and production settings before use.'],
  }),
  snapshotSkill({
    slug: 'pluviobyte-ra-topic',
    name: 'RNSkill Topic Router',
    description: 'Route a content idea through topic capture, research, production planning, publishing, and archive steps for a video content workspace.',
    longDescription:
      'A source-checked workflow from Pluviobyte/rnskill for turning a natural-language content idea into a structured topic card and routing it to a video, article, image, or practical long-form production workflow. It is designed around that repository\'s workspace conventions, so use it as a planning reference and adapt file paths, data sources, and publishing controls before using it outside the original environment.',
    repo: 'Pluviobyte/rnskill',
    repository: 'https://github.com/Pluviobyte/rnskill/tree/main/skills/ra-选题',
    installCommand: 'npx -y skills add Pluviobyte/rnskill --skill ra-选题',
    category: 'Video Creation',
    tags: ['agent-skill', 'video-production', 'content-planning', 'topic-research', 'creator-workflow'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 797,
    forks: 89,
    language: 'Markdown',
    quality: 78,
    reviewScore: 75,
    verified: false,
    license: 'CC-BY-NC-4.0 (repository; verify skill-level terms)',
    lastPushedAt: '2026-07-27T09:47:32.000Z',
    reviewIssues: ['Repository content is licensed non-commercially; confirm the intended use before commercial reuse.', 'This workflow assumes repository-specific workspace paths and needs adaptation before unattended use.'],
    reviewSuggestions: ['Start with a single approved brief in a sandbox project.', 'Replace repository-specific paths with the local production workspace before use.'],
  }),
  snapshotSkill({
    slug: 'pluviobyte-ra-practical-video-planning',
    name: 'RNSkill Practical Video Planning',
    description: 'Plan a practical long-form video with test prompts, recording structure, narration beats, screen-recording steps, and production handoff.',
    longDescription:
      'A source-checked Pluviobyte/rnskill skill for planning Bilibili or YouTube-style practical videos. It organizes a test matrix, on-camera script, recording checklist, hooks, and handoff stages for an editor. It is a planning framework, not a guarantee of publish-ready output: creators should validate claims, samples, rights, and the production environment before recording or publishing.',
    repo: 'Pluviobyte/rnskill',
    repository: 'https://github.com/Pluviobyte/rnskill/tree/main/skills/ra-实操策划',
    installCommand: 'npx -y skills add Pluviobyte/rnskill --skill ra-实操策划',
    category: 'Video Creation',
    tags: ['agent-skill', 'video-planning', 'content-strategy', 'recording', 'screen-recording', 'creator-workflow'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 797,
    forks: 89,
    language: 'Markdown',
    quality: 78,
    reviewScore: 75,
    verified: false,
    license: 'CC-BY-NC-4.0 (repository; verify skill-level terms)',
    lastPushedAt: '2026-07-27T09:47:32.000Z',
    reviewIssues: ['Repository content is licensed non-commercially; confirm the intended use before commercial reuse.', 'Human review is required for factual claims, benchmarks, and the final recording plan.'],
    reviewSuggestions: ['Validate every test prompt and source claim before recording.', 'Use it as an editable plan rather than an autonomous publishing workflow.'],
  }),
  snapshotSkill({
    slug: 'pluviobyte-ra-video-title',
    name: 'RNSkill Video Title',
    description: 'Generate topic-first, two-part video-title candidates from an approved video brief or final script.',
    longDescription:
      'A source-checked Pluviobyte/rnskill workflow for deriving a video theme, studying approved benchmark patterns, producing title candidates, and retaining the final human choice. It is useful for ideation and packaging, but should not be used to copy another creator\'s title, identity, or copyrighted wording. Keep a human in the approval loop for platform fit and truthfulness.',
    repo: 'Pluviobyte/rnskill',
    repository: 'https://github.com/Pluviobyte/rnskill/tree/main/skills/ra-video-title',
    installCommand: 'npx -y skills add Pluviobyte/rnskill --skill ra-video-title',
    category: 'Video Creation',
    tags: ['agent-skill', 'video-title', 'content-packaging', 'copywriting', 'creator-workflow'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 797,
    forks: 89,
    language: 'Markdown',
    quality: 79,
    reviewScore: 76,
    verified: false,
    license: 'CC-BY-NC-4.0 (repository; verify skill-level terms)',
    lastPushedAt: '2026-07-27T09:47:32.000Z',
    reviewIssues: ['Repository content is licensed non-commercially; confirm the intended use before commercial reuse.', 'Review titles for accuracy and avoid copying another creator\'s identity or expression.'],
    reviewSuggestions: ['Use approved source material and a clear video theme.', 'Keep final title selection with a human publisher.'],
  }),
  snapshotSkill({
    slug: 'pluviobyte-tts-skill',
    name: 'RNSkill Local TTS Narration',
    description: 'Generate a controlled local narration workflow with auditions, version tracking, and subtitle-ready final audio.',
    longDescription:
      'A source-checked Pluviobyte/rnskill workflow for local IndexTTS2 narration in its own content workspace. It emphasizes canonical voice references, audition approval, lossless audio, and a handoff to real-timestamp subtitles. Treat voice cloning and narrator references as consent-sensitive: only use voices you own or are authorized to use, and adapt local model, hardware, and file assumptions before installation.',
    repo: 'Pluviobyte/rnskill',
    repository: 'https://github.com/Pluviobyte/rnskill/tree/main/skills/tts-skill',
    installCommand: 'npx -y skills add Pluviobyte/rnskill --skill tts-skill',
    category: 'Video Creation',
    tags: ['agent-skill', 'tts', 'voiceover', 'voice-cloning', 'video-production', 'audio'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 797,
    forks: 89,
    language: 'Python',
    quality: 68,
    reviewScore: 64,
    verified: false,
    license: 'CC-BY-NC-4.0 (repository; verify skill-level terms)',
    lastPushedAt: '2026-07-27T09:47:32.000Z',
    reviewIssues: ['Voice cloning requires explicit rights and consent for every speaker reference.', 'The documented workflow depends on local models, hardware, and repository-specific files.', 'Repository content is licensed non-commercially; confirm the intended use before commercial reuse.'],
    reviewSuggestions: ['Use only authorized voice samples.', 'Run a short audition in a sandbox before producing or publishing a final narration.'],
  }),
  snapshotSkill({
    slug: 'pluviobyte-heygen-digital-avatar',
    name: 'RNSkill HeyGen Digital Avatar',
    description: 'Create a consent-aware digital-avatar layer for AI video production with narration approval and final quality gates.',
    longDescription:
      'A source-checked Pluviobyte/rnskill workflow for HeyGen digital-human video generation. It specifies avatar selection, local narration, subtitle-safe layout, paid-generation gates, and final QC. It relies on a configured HeyGen account, subscription credits, avatar assets, and a Digital Twin profile. Use it only with explicit rights to the likeness and voice, and retain human review before any paid or public generation.',
    repo: 'Pluviobyte/rnskill',
    repository: 'https://github.com/Pluviobyte/rnskill/tree/main/skills/heygen-digital-avatar',
    installCommand: 'npx -y skills add Pluviobyte/rnskill --skill heygen-digital-avatar',
    category: 'Video Creation',
    tags: ['agent-skill', 'heygen', 'digital-avatar', 'talking-head', 'video-generation', 'voiceover'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh', 'HeyGen'],
    stars: 797,
    forks: 89,
    language: 'Markdown',
    quality: 64,
    reviewScore: 60,
    verified: false,
    license: 'CC-BY-NC-4.0 (repository; verify skill-level terms)',
    lastPushedAt: '2026-07-27T09:47:32.000Z',
    reviewIssues: ['Requires a paid third-party service, OAuth or API access, and explicit spending approval.', 'Digital-avatar and voice use requires explicit likeness and consent rights.', 'Repository content is licensed non-commercially; confirm the intended use before commercial reuse.'],
    reviewSuggestions: ['Approve the exact narration before starting a paid generation.', 'Use a test avatar and sandbox account before production use.'],
  }),
  snapshotSkill({
    slug: 'pluviobyte-ra-local-talking-head-cut',
    name: 'RNSkill Local Talking-Head Cut',
    description: 'Build a reproducible local rough-cut workflow for talking-head or narrated screen-recording videos with transcript review gates.',
    longDescription:
      'A source-checked Pluviobyte/rnskill skill for cleaning spoken video, correcting supported terminology, compressing pauses, normalizing dialogue, and preparing a human-approved rough cut. It uses ASR, local editing scripts, and repository-specific artifacts. Keep the source resolution, retain the original media, and stop for human approval before any semantic deletion or final render.',
    repo: 'Pluviobyte/rnskill',
    repository: 'https://github.com/Pluviobyte/rnskill/tree/main/skills/ra-local-talking-head-cut',
    installCommand: 'npx -y skills add Pluviobyte/rnskill --skill ra-local-talking-head-cut',
    category: 'Video Creation',
    tags: ['agent-skill', 'talking-head', 'video-editing', 'transcript', 'rough-cut', 'asr'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 797,
    forks: 89,
    language: 'Python',
    quality: 76,
    reviewScore: 71,
    verified: false,
    license: 'CC-BY-NC-4.0 (repository; verify skill-level terms)',
    lastPushedAt: '2026-07-27T09:47:32.000Z',
    reviewIssues: ['May require external ASR credentials and upload access for source media.', 'Human approval is required before semantic edits, deletion, or rendering.', 'Repository content is licensed non-commercially; confirm the intended use before commercial reuse.'],
    reviewSuggestions: ['Use approved media only and preserve an original copy.', 'Review the generated transcript before cutting or publishing.'],
  }),
  snapshotSkill({
    slug: 'pluviobyte-ra-audio-to-subtitles',
    name: 'RNSkill Audio to Subtitles',
    description: 'Generate real-timestamp subtitle artifacts from final narration audio or merged video with a caption quality gate.',
    longDescription:
      'A source-checked Pluviobyte/rnskill skill for creating subtitle artifacts from final audio using ASR word timestamps, phrase checks, SRT/VTT export, and a caption QC report. It correctly treats the final audio stream as the timing source instead of estimating timings from script length. External ASR credentials and media privacy must be reviewed before upload or execution.',
    repo: 'Pluviobyte/rnskill',
    repository: 'https://github.com/Pluviobyte/rnskill/tree/main/skills/ra-audio-to-subtitles',
    installCommand: 'npx -y skills add Pluviobyte/rnskill --skill ra-audio-to-subtitles',
    category: 'Video Creation',
    tags: ['agent-skill', 'subtitles', 'captions', 'asr', 'srt', 'vtt', 'video-production'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 797,
    forks: 89,
    language: 'Python',
    quality: 75,
    reviewScore: 71,
    verified: false,
    license: 'CC-BY-NC-4.0 (repository; verify skill-level terms)',
    lastPushedAt: '2026-07-27T09:47:32.000Z',
    reviewIssues: ['External ASR may require API credentials and may process uploaded media.', 'Repository content is licensed non-commercially; confirm the intended use before commercial reuse.'],
    reviewSuggestions: ['Use the final approved audio only.', 'Confirm ASR vendor privacy and data-retention settings before upload.'],
  }),
  snapshotSkill({
    slug: 'pluviobyte-skill-captions',
    name: 'RNSkill Production Captions',
    description: 'Render, preview, validate, and burn consistent production subtitles from quality-checked timestamp artifacts.',
    longDescription:
      'A source-checked Pluviobyte/rnskill skill for the visual layer of captions: typography, panel geometry, preview rendering, burn-in, portable subtitle exports, and output QC. It is intended to follow a validated timing workflow such as Audio to Subtitles. Review typographic choices, readability, language support, and final render output before a video is published.',
    repo: 'Pluviobyte/rnskill',
    repository: 'https://github.com/Pluviobyte/rnskill/tree/main/skills/skill-captions',
    installCommand: 'npx -y skills add Pluviobyte/rnskill --skill skill-captions',
    category: 'Video Creation',
    tags: ['agent-skill', 'captions', 'subtitles', 'typography', 'rendering', 'video-production'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 797,
    forks: 89,
    language: 'Python',
    quality: 78,
    reviewScore: 74,
    verified: false,
    license: 'CC-BY-NC-4.0 (repository; verify skill-level terms)',
    lastPushedAt: '2026-07-27T09:47:32.000Z',
    reviewIssues: ['The documented caption style is repository-specific and needs visual review in the target format.', 'Repository content is licensed non-commercially; confirm the intended use before commercial reuse.'],
    reviewSuggestions: ['Generate a still preview before rendering the full video.', 'Keep editable subtitle files alongside the final burn-in.'],
  }),
  snapshotSkill({
    slug: 'pluviobyte-rn-cover-skill',
    name: 'RNSkill Editorial Video Cover',
    description: 'Create original editorial technology covers with a controlled layout, custom diagram generation, and editable SVG or PNG output.',
    longDescription:
      'A source-checked Pluviobyte/rnskill workflow for creating a fresh, editorial-style visual cover from a written design contract. It uses generated right-side art, controlled typography, a warm-white canvas, and layout QC. It requires original output rather than reproducing a reference image, and any generated asset should be reviewed for brand rights, model terms, and platform fit before publication.',
    repo: 'Pluviobyte/rnskill',
    repository: 'https://github.com/Pluviobyte/rnskill/tree/main/skills/rn-cover-skill',
    installCommand: 'npx -y skills add Pluviobyte/rnskill --skill rn-cover-skill',
    category: 'Video Creation',
    tags: ['agent-skill', 'video-cover', 'thumbnail', 'editorial-design', 'svg', 'image-generation'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh', 'Image generation'],
    stars: 797,
    forks: 89,
    language: 'Python',
    quality: 78,
    reviewScore: 74,
    verified: false,
    license: 'CC-BY-NC-4.0 (repository; verify skill-level terms)',
    lastPushedAt: '2026-07-27T09:47:32.000Z',
    reviewIssues: ['Generated covers require a human review for text fit, branding, and asset rights.', 'Repository content is licensed non-commercially; confirm the intended use before commercial reuse.'],
    reviewSuggestions: ['Use original output rather than copying a reference image.', 'Review the final asset at the target social-platform crop.'],
  }),
  snapshotSkill({
    slug: 'pluviobyte-ra-retrospective',
    name: 'RNSkill Content Retrospective',
    description: 'Turn creator performance data into a documented retrospective, grounded hypotheses, and reusable content learnings.',
    longDescription:
      'A source-checked Pluviobyte/rnskill workflow for reviewing published content performance, comparing it with recent baselines, tracing evidence, and saving a useful lesson for future briefs. It assumes access to platform metrics, content records, and repository-specific assets. Do not connect private dashboards or account data until the data boundary and permissions have been reviewed.',
    repo: 'Pluviobyte/rnskill',
    repository: 'https://github.com/Pluviobyte/rnskill/tree/main/skills/ra-复盘',
    installCommand: 'npx -y skills add Pluviobyte/rnskill --skill ra-复盘',
    category: 'Video Creation',
    tags: ['agent-skill', 'content-analytics', 'retrospective', 'creator-workflow', 'metrics', 'video-production'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 797,
    forks: 89,
    language: 'Markdown',
    quality: 74,
    reviewScore: 70,
    verified: false,
    license: 'CC-BY-NC-4.0 (repository; verify skill-level terms)',
    lastPushedAt: '2026-07-27T09:47:32.000Z',
    reviewIssues: ['The workflow can touch private platform metrics and workspace files; review the data boundary first.', 'Repository content is licensed non-commercially; confirm the intended use before commercial reuse.'],
    reviewSuggestions: ['Use exported, approved metrics in a sandbox before connecting account data.', 'Treat the output as a hypothesis and keep the final editorial conclusion human-reviewed.'],
  }),
  snapshotSkill({
    slug: 'anthropic-earnings-analysis',
    name: 'Equity Research Earnings Analysis',
    description: 'Create a structured post-earnings equity research update with key metrics, estimate changes, charts, and thesis review.',
    longDescription:
      'A source-checked financial research skill from Anthropic Financial Services for turning reported quarterly results into a disciplined earnings update. It is useful for analyzing a company already under coverage, but it depends on accurate source financials and should be reviewed by a qualified human before it informs an investment decision or external publication.',
    repo: 'anthropics/financial-services',
    repository: 'https://github.com/anthropics/financial-services/tree/main/plugins/vertical-plugins/equity-research/skills/earnings-analysis',
    installCommand: 'npx -y skills add anthropics/financial-services --skill earnings-analysis',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'equity-research', 'earnings', 'fundamental-analysis', 'financial-modeling'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh'],
    stars: 34_158,
    quality: 92,
    reviewScore: 86,
    verified: false,
    license: 'Apache-2.0',
    lastPushedAt: '2026-08-04T00:00:00.000Z',
    reviewIssues: ['Financial research output is not financial advice; a human must review source data and conclusions before a live investment decision.'],
    reviewSuggestions: ['Use company filings and approved data sources as evidence.', 'Do not turn the output into an automated trade or public recommendation.'],
  }),
  snapshotSkill({
    slug: 'anthropic-portfolio-monitoring',
    name: 'Portfolio Monitoring',
    description: 'Review portfolio-company financial packages, flag variance to plan, and prepare monitored KPI summaries.',
    longDescription:
      'A source-checked financial monitoring workflow from Anthropic Financial Services. It extracts KPIs from approved Excel, PDF, or CSV financial packages and compares them with prior periods and budgets; because these materials may contain confidential data and covenants, keep the run inside an approved workspace and have a responsible analyst validate every conclusion.',
    repo: 'anthropics/financial-services',
    repository: 'https://github.com/anthropics/financial-services/tree/main/plugins/agent-plugins/valuation-reviewer/skills/portfolio-monitoring',
    installCommand: 'npx -y skills add anthropics/financial-services --skill portfolio-monitoring',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'portfolio-monitoring', 'kpi', 'financial-statements', 'board-reporting'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh'],
    stars: 34_158,
    quality: 90,
    reviewScore: 84,
    verified: false,
    license: 'Apache-2.0',
    lastPushedAt: '2026-08-04T00:00:00.000Z',
    reviewIssues: ['The workflow can process confidential portfolio financial packages; review data access and retention before use.'],
    reviewSuggestions: ['Run with an approved, minimized financial package first.', 'Validate covenant and budget variance conclusions with the portfolio owner.'],
  }),
  snapshotSkill({
    slug: 'anthropic-three-statement-model',
    name: '3-Statement Financial Model',
    description: 'Complete and link income statement, balance sheet, and cash flow statement model templates with formulas and checks.',
    longDescription:
      'A source-checked financial modeling skill from Anthropic Financial Services for completing an integrated three-statement workbook. It may write formulas and produce spreadsheet output, so use a copy of the template, review every assumption and formula, and never treat a generated model as a substitute for accounting, audit, or investment review.',
    repo: 'anthropics/financial-services',
    repository: 'https://github.com/anthropics/financial-services/tree/main/plugins/vertical-plugins/financial-analysis/skills/3-statement-model',
    installCommand: 'npx -y skills add anthropics/financial-services --skill 3-statement-model',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'financial-modeling', 'three-statement', 'excel', 'cash-flow'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh', 'Excel'],
    stars: 34_158,
    quality: 89,
    reviewScore: 82,
    verified: false,
    license: 'Apache-2.0',
    lastPushedAt: '2026-08-04T00:00:00.000Z',
    reviewIssues: ['The workflow can write spreadsheet formulas and should be run on a copy of the source model.'],
    reviewSuggestions: ['Reconcile generated formulas and balance-sheet checks before sharing the model.', 'Keep financial assumptions human-owned.'],
  }),
  snapshotSkill({
    slug: 'geeksfino-financial-statement-analyzer',
    name: 'Financial Statement Analyzer',
    description: 'Perform a forensic company financial-statement review across earnings quality, health, fraud risk, and operating efficiency.',
    longDescription:
      'A source-checked finance research skill from Geeksfino for deep analysis of one companys income statement, balance sheet, and cash flow statement. It is particularly useful for earnings-quality, working-capital, Altman Z-score, and Beneish M-score research, but the outputs are analytical hypotheses that require verified source data and human validation.',
    repo: 'Geeksfino/finskills',
    repository: 'https://github.com/Geeksfino/finskills/tree/main/US-market/financial-statement-analyzer',
    installCommand: 'npx -y skills add Geeksfino/finskills --skill financial-statement-analyzer',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'financial-statements', 'forensic-accounting', 'fundamental-analysis', 'risk-analysis'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh'],
    stars: 271,
    quality: 84,
    reviewScore: 78,
    verified: false,
    license: 'Apache-2.0',
    lastPushedAt: '2026-03-05T00:00:00.000Z',
    reviewIssues: ['Repository freshness is limited; validate all formulas, thresholds, and market data before use.'],
    reviewSuggestions: ['Use current filings from an approved source.', 'Treat fraud-risk flags as prompts for review, not findings of fact.'],
  }),
  snapshotSkill({
    slug: 'geeksfino-quant-factor-screener',
    name: 'Quant Factor Screener',
    description: 'Screen equities with systematic value, momentum, quality, volatility, size, and growth factor frameworks.',
    longDescription:
      'A source-checked Geeksfino quantitative research skill for building a transparent multi-factor screening workflow. It can help an agent rank a defined universe based on stated factor assumptions, but factor outputs depend on point-in-time data, universe construction, and rebalancing assumptions and must not drive autonomous investment activity.',
    repo: 'Geeksfino/finskills',
    repository: 'https://github.com/Geeksfino/finskills/tree/main/US-market/quant-factor-screener',
    installCommand: 'npx -y skills add Geeksfino/finskills --skill quant-factor-screener',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'quant', 'factor-investing', 'equity-screening', 'portfolio-research'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh'],
    stars: 271,
    quality: 83,
    reviewScore: 77,
    verified: false,
    license: 'Apache-2.0',
    lastPushedAt: '2026-03-05T00:00:00.000Z',
    reviewIssues: ['Repository freshness is limited; factor exposures and source data must be independently verified.'],
    reviewSuggestions: ['Use point-in-time data and document the screened universe.', 'Validate results with a human investment research workflow.'],
  }),
  snapshotSkill({
    slug: 'geeksfino-portfolio-health-check',
    name: 'Portfolio Health Check',
    description: 'Audit concentration, factor exposure, correlation, liquidity, and stress-test risks in an existing portfolio.',
    longDescription:
      'A source-checked Geeksfino portfolio diagnostic skill that helps structure a risk review around concentration, factor tilts, correlations, liquidity gaps, and stress scenarios. It should be used as a research checklist for an approved holdings dataset, not as an autonomous rebalance engine or personalized investment recommendation.',
    repo: 'Geeksfino/finskills',
    repository: 'https://github.com/Geeksfino/finskills/tree/main/US-market/portfolio-health-check',
    installCommand: 'npx -y skills add Geeksfino/finskills --skill portfolio-health-check',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'portfolio', 'risk-management', 'stress-testing', 'factor-exposure'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh'],
    stars: 271,
    quality: 82,
    reviewScore: 76,
    verified: false,
    license: 'Apache-2.0',
    lastPushedAt: '2026-03-05T00:00:00.000Z',
    reviewIssues: ['Portfolio and suitability conclusions require human review and up-to-date holdings data.'],
    reviewSuggestions: ['Use a sanitized or approved holdings export.', 'Document assumptions for concentration and stress-test thresholds.'],
  }),
  snapshotSkill({
    slug: 'tradermonty-market-environment-analysis',
    name: 'Market Environment Analysis',
    description: 'Create a global market conditions report spanning equities, rates, FX, commodities, risk appetite, and sector rotation.',
    longDescription:
      'A source-checked research skill from TraderMonty for structuring daily or weekly market-environment briefings. It combines cross-asset conditions, economic indicators, sector context, and technical interpretation, but it must use current cited data and remain a human-reviewed research artifact rather than a directive to trade.',
    repo: 'tradermonty/claude-trading-skills',
    repository: 'https://github.com/tradermonty/claude-trading-skills/tree/main/skills/market-environment-analysis',
    installCommand: 'npx -y skills add tradermonty/claude-trading-skills --skill market-environment-analysis',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'market-analysis', 'macro', 'sector-rotation', 'risk-on-risk-off'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh'],
    stars: 2_602,
    quality: 84,
    reviewScore: 79,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-08-10T00:00:00.000Z',
    reviewIssues: ['Market commentary can become stale quickly; verify time-sensitive figures and sources before relying on it.'],
    reviewSuggestions: ['Cite the date and primary source for every material market input.', 'Keep trade execution outside this research workflow.'],
  }),
  snapshotSkill({
    slug: 'tradermonty-market-news-analyst',
    name: 'Market News Analyst',
    description: 'Rank recent market-moving news and explain likely effects on equities, commodities, monetary policy, and earnings.',
    longDescription:
      'A source-checked financial news analysis skill from TraderMonty that uses web search and web fetch tools to produce an impact-ranked briefing. It is designed for fast research around monetary policy, geopolitical developments, commodity moves, and mega-cap earnings, with a required fact and timestamp review before distribution or decision use.',
    repo: 'tradermonty/claude-trading-skills',
    repository: 'https://github.com/tradermonty/claude-trading-skills/tree/main/skills/market-news-analyst',
    installCommand: 'npx -y skills add tradermonty/claude-trading-skills --skill market-news-analyst',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'market-news', 'macro', 'earnings', 'web-research'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh', 'Web search'],
    stars: 2_602,
    quality: 84,
    reviewScore: 79,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-08-10T00:00:00.000Z',
    reviewIssues: ['The output depends on web-source quality and freshness; verify claims against primary sources.'],
    reviewSuggestions: ['Keep source links and timestamps in the final briefing.', 'Separate observed facts from scenario interpretation.'],
  }),
  snapshotSkill({
    slug: 'tradermonty-earnings-calendar',
    name: 'Earnings Calendar',
    description: 'Build an upcoming US earnings calendar with dates, timing, consensus estimates, and market-impact context.',
    longDescription:
      'A source-checked TraderMonty research skill for producing a focused weekly earnings calendar from Financial Modeling Prep data. It requires an external data provider configuration and data-license review, and results should be checked against company investor-relations calendars before an agent or person acts on them.',
    repo: 'tradermonty/claude-trading-skills',
    repository: 'https://github.com/tradermonty/claude-trading-skills/tree/main/skills/earnings-calendar',
    installCommand: 'npx -y skills add tradermonty/claude-trading-skills --skill earnings-calendar',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'earnings', 'calendar', 'market-data', 'research'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh', 'Financial Modeling Prep'],
    stars: 2_602,
    quality: 82,
    reviewScore: 76,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-08-10T00:00:00.000Z',
    reviewIssues: ['Requires Financial Modeling Prep access; verify account scope, provider terms, and event dates before use.'],
    reviewSuggestions: ['Compare important events with company investor-relations calendars.', 'Keep provider keys outside prompts and source repositories.'],
  }),
  snapshotSkill({
    slug: 'tradermonty-us-stock-analysis',
    name: 'US Stock Analysis',
    description: 'Research a US equity across fundamentals, valuation, technical context, peers, and current market data.',
    longDescription:
      'A source-checked TraderMonty skill for assembling a structured US equity research report. It combines financial metrics, business-quality analysis, valuation, technical context, and peer comparisons, but current facts must come from cited sources and the completed analysis must remain human-reviewed rather than becoming an automated buy or sell recommendation.',
    repo: 'tradermonty/claude-trading-skills',
    repository: 'https://github.com/tradermonty/claude-trading-skills/tree/main/skills/us-stock-analysis',
    installCommand: 'npx -y skills add tradermonty/claude-trading-skills --skill us-stock-analysis',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'stock-analysis', 'fundamental-analysis', 'valuation', 'equity-research'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh', 'Web search'],
    stars: 2_602,
    quality: 83,
    reviewScore: 77,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-08-10T00:00:00.000Z',
    reviewIssues: ['Financial output is research only and must not be used as personalized investment advice.'],
    reviewSuggestions: ['Use filings and primary data for material claims.', 'Record assumptions and valuation dates in the final report.'],
  }),
  snapshotSkill({
    slug: 'alphagbm-stock-analysis',
    name: 'AlphaGBM Stock Analysis',
    description: 'Analyze a ticker with AlphaGBMs five-pillar framework: fundamentals, technicals, sentiment, flows, and valuation.',
    longDescription:
      'A source-checked stock-research skill from AlphaGBM that organizes public market data into a five-pillar score and research narrative. It may call an external AlphaGBM service, so agents must review provider terms, protect credentials, validate the underlying facts, and keep the output within a human-approved investment-research process.',
    repo: 'AlphaGBM/skills',
    repository: 'https://github.com/AlphaGBM/skills/tree/main/skills/alphagbm-stock-analysis',
    installCommand: 'npx -y skills add AlphaGBM/skills --skill alphagbm-stock-analysis',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'stock-analysis', 'fundamentals', 'sentiment', 'valuation'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh', 'AlphaGBM API'],
    stars: 1_763,
    quality: 82,
    reviewScore: 76,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-07-09T00:00:00.000Z',
    reviewIssues: ['Uses an external market-data service; review provider terms, credentials, and point-in-time data quality.'],
    reviewSuggestions: ['Validate scores against the cited underlying data.', 'Do not turn a composite score into an autonomous trade.'],
  }),
  snapshotSkill({
    slug: 'gauss314-fred-macro',
    name: 'FRED Macro Data',
    description: 'Retrieve official Federal Reserve economic series for GDP, inflation, rates, employment, money supply, and volatility research.',
    longDescription:
      'A source-checked Gauss314 skill for working with the Federal Reserve Bank of St. Louis FRED API. It helps agents pull transparent macroeconomic time series for an analysis workflow, but API access, revisions, transformations, and time alignment must be verified before the results feed a decision or public market commentary.',
    repo: 'gauss314/skills',
    repository: 'https://github.com/gauss314/skills/tree/main/skills/fred-macro',
    installCommand: 'npx -y skills add gauss314/skills --skill fred-macro',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'macro', 'fred', 'economic-data', 'rates'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh', 'FRED API'],
    stars: 175,
    quality: 80,
    reviewScore: 75,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-06-14T00:00:00.000Z',
    reviewIssues: ['FRED data can be revised and requires documented series transformations and dates.'],
    reviewSuggestions: ['Store series identifiers and retrieval timestamps with the output.', 'Validate revisions before comparing periods.'],
  }),
  snapshotSkill({
    slug: 'gauss314-yahoo-finance',
    name: 'Yahoo Finance Data',
    description: 'Retrieve market prices, histories, fundamentals, options, and news through Yahoo Finance endpoints for research workflows.',
    longDescription:
      'A source-checked Gauss314 skill for collecting market data through Yahoo Finance endpoints without a wrapper. It can be useful for quick research across stocks, ETFs, indices, FX, and options, but users must verify data quality and the applicable provider terms before any production or decision-critical use.',
    repo: 'gauss314/skills',
    repository: 'https://github.com/gauss314/skills/tree/main/skills/yahoo-finance',
    installCommand: 'npx -y skills add gauss314/skills --skill yahoo-finance',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'market-data', 'stocks', 'fundamentals', 'options'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh', 'Yahoo Finance'],
    stars: 175,
    quality: 78,
    reviewScore: 72,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-06-14T00:00:00.000Z',
    reviewIssues: ['Yahoo Finance endpoints are unofficial; verify data accuracy, availability, and provider terms before production use.'],
    reviewSuggestions: ['Use a licensed primary source for critical figures.', 'Log the retrieval date and endpoint used.'],
  }),
  snapshotSkill({
    slug: 'joellewis-qualitative-valuation',
    name: 'Qualitative Valuation',
    description: 'Assess business quality, economic moats, management, competitive positioning, and durable value creation.',
    longDescription:
      'A source-checked finance skill from JoelLewis for framing qualitative company valuation around moats, governance, management quality, and competitive dynamics. It is a useful complement to financial models, but it is only a structured reasoning aid and must be backed by current primary evidence and human investment judgment.',
    repo: 'JoelLewis/finance_skills',
    repository: 'https://github.com/JoelLewis/finance_skills/tree/main/plugins/wealth-management/skills/qualitative-valuation',
    installCommand: 'npx -y skills add JoelLewis/finance_skills --skill qualitative-valuation',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'valuation', 'economic-moat', 'business-quality', 'equity-research'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh'],
    stars: 164,
    quality: 81,
    reviewScore: 75,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-07-18T00:00:00.000Z',
    reviewIssues: ['Qualitative conclusions can be subjective and require cited evidence and human challenge.'],
    reviewSuggestions: ['Separate sourced facts from interpretive judgments.', 'Use current filings, transcripts, and competitive evidence.'],
  }),
  snapshotSkill({
    slug: 'star23-tech-earnings-deepdive',
    name: 'Tech Earnings Deep Dive',
    description: 'Create a multi-perspective technology-company earnings memo with evidence standards, valuation lenses, and anti-bias checks.',
    longDescription:
      'A source-checked Day1Global skill for an institutional-style technology earnings review. It brings together primary earnings evidence, valuation frameworks, management context, competitive analysis, and explicit anti-bias steps; it remains a research workflow and should not generate automated position changes or personalized financial advice.',
    repo: 'star23/Day1Global-Skills',
    repository: 'https://github.com/star23/Day1Global-Skills/tree/main/tech-earnings-deepdive',
    installCommand: 'npx -y skills add star23/Day1Global-Skills --skill tech-earnings-deepdive',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'tech-stocks', 'earnings', 'investment-memo', 'valuation'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 1_027,
    quality: 80,
    reviewScore: 74,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-04-15T00:00:00.000Z',
    reviewIssues: ['Repository freshness is limited; validate market facts, rules, and valuation assumptions against current primary sources.'],
    reviewSuggestions: ['Use the anti-bias checklist and cite primary evidence.', 'Keep final position sizing and execution outside the skill.'],
  }),
  snapshotSkill({
    slug: 'himself65-company-valuation',
    name: 'Company Valuation',
    description: 'Estimate a public companys intrinsic value through DCF, relative, and sum-of-the-parts valuation methods.',
    longDescription:
      'A source-checked company valuation skill from himself65 that triangulates DCF, peer multiple, and sum-of-the-parts methods into a transparent research output. It is useful for preparing an analyst draft, but any generated share-price estimate is sensitive to assumptions and must be independently reviewed before it is used in a financial decision.',
    repo: 'himself65/finance-skills',
    repository: 'https://github.com/himself65/finance-skills/tree/main/plugins/market-analysis/skills/company-valuation',
    installCommand: 'npx -y skills add himself65/finance-skills --skill company-valuation',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'valuation', 'dcf', 'peer-comparison', 'sum-of-the-parts'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh'],
    stars: 3_139,
    quality: 85,
    reviewScore: 80,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-08-05T00:00:00.000Z',
    reviewIssues: ['Valuation outputs are highly assumption-sensitive and are not financial advice.'],
    reviewSuggestions: ['Keep input assumptions visible in the final model.', 'Run sensitivity analysis before comparing companies.'],
  }),
  snapshotSkill({
    slug: 'himself65-earnings-preview',
    name: 'Earnings Preview',
    description: 'Prepare a pre-earnings briefing with consensus estimates, beat-miss history, and current market context.',
    longDescription:
      'A source-checked finance research skill from himself65 for preparing an evidence-led pre-earnings brief. It uses Yahoo Finance data and market expectations, so results require provider-term awareness, source verification, and a human review before any result is published or used in an investment decision.',
    repo: 'himself65/finance-skills',
    repository: 'https://github.com/himself65/finance-skills/tree/main/plugins/market-analysis/skills/earnings-preview',
    installCommand: 'npx -y skills add himself65/finance-skills --skill earnings-preview',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'earnings', 'stock-analysis', 'consensus-estimates', 'market-data'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh', 'Yahoo Finance'],
    stars: 3_139,
    quality: 83,
    reviewScore: 78,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-08-05T00:00:00.000Z',
    reviewIssues: ['Uses external market data; verify timing, data quality, and provider terms before relying on results.'],
    reviewSuggestions: ['Check dates with the company investor-relations calendar.', 'Keep the final summary clear about assumptions and uncertainty.'],
  }),
  snapshotSkill({
    slug: 'tushare-finance',
    name: 'Tushare Finance',
    description: 'Access China, Hong Kong, US, fund, futures, bond, and macroeconomic data through Tushare Pro workflows.',
    longDescription:
      'A source-checked China-market finance skill for Claude Code and compatible agents that accesses Tushare Pro data across equities, funds, futures, bonds, statements, and macro indicators. It requires a Tushare token and responsible handling of provider credentials; data use and financial conclusions must be reviewed before any live decision.',
    repo: 'StanleyChanH/Tushare-Finance-Skill-for-Claude-Code',
    repository: 'https://github.com/StanleyChanH/Tushare-Finance-Skill-for-Claude-Code/tree/master',
    installCommand: 'npx -y skills add StanleyChanH/Tushare-Finance-Skill-for-Claude-Code --skill tushare-finance',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'china-market', 'a-shares', 'market-data', 'tushare'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh', 'Tushare Pro'],
    stars: 76,
    quality: 80,
    reviewScore: 75,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-08-10T00:00:00.000Z',
    reviewIssues: ['Requires a Tushare Pro token; protect credentials and verify provider permissions before use.'],
    reviewSuggestions: ['Use an environment variable for the token.', 'Record the source endpoint and data timestamp in research output.'],
  }),
  snapshotSkill({
    slug: 'alphaear-stock',
    name: 'AlphaEar Stock Data',
    description: 'Look up A-share, Hong Kong, and US stock tickers and retrieve historical OHLCV price data for research.',
    longDescription:
      'A source-checked finance data skill from Awesome Finance Skills for ticker lookup and historical OHLCV research across China, Hong Kong, and US markets. It is appropriate for data exploration and charting inputs, but pricing data can be delayed or adjusted and should be validated against an approved market-data source in any professional workflow.',
    repo: 'RKiding/Awesome-finance-skills',
    repository: 'https://github.com/RKiding/Awesome-finance-skills/tree/main/skills/alphaear-stock',
    installCommand: 'npx -y skills add RKiding/Awesome-finance-skills --skill alphaear-stock',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'market-data', 'a-shares', 'hong-kong-stocks', 'ohlcv'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 2_768,
    quality: 79,
    reviewScore: 74,
    verified: false,
    license: 'Apache-2.0',
    lastPushedAt: '2026-03-29T00:00:00.000Z',
    reviewIssues: ['Repository freshness is limited; validate price adjustments, market calendar handling, and data-source terms.'],
    reviewSuggestions: ['Confirm ticker mapping before analysis.', 'Use an approved data source for time-sensitive figures.'],
  }),
  snapshotSkill({
    slug: 'simons-quant',
    name: 'Simons Quant',
    description: 'Evaluate systematic strategy ideas through signal testing, statistical validation, decay, execution costs, and model-risk review.',
    longDescription:
      'A source-checked InvestorSkills quantitative research skill inspired by a Renaissance-style approach to robust signal research. It helps agents turn intuition into testable hypotheses, examine overfitting and signal decay, and structure portfolio construction review; it must never be treated as a ready-to-trade strategy without independent validation and human control.',
    repo: 'xuboyuebobb/investorskills',
    repository: 'https://github.com/xuboyuebobb/investorskills/tree/main/skills/simons-quant',
    installCommand: 'npx -y skills add xuboyuebobb/investorskills --skill simons-quant',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'quant', 'signal-research', 'backtesting', 'model-risk'],
    frameworks: ['Codex', 'Claude Code', 'skills.sh'],
    stars: 811,
    quality: 80,
    reviewScore: 75,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-07-14T00:00:00.000Z',
    reviewIssues: ['Quantitative strategy research requires point-in-time data, transaction-cost assumptions, and out-of-sample validation.'],
    reviewSuggestions: ['Keep backtest code and assumptions reproducible.', 'Use a sandbox before considering any live capital.'],
  }),
  snapshotSkill({
    slug: 'trade-fundamental',
    name: 'Fundamental Analysis Agent',
    description: 'Research a companys valuation, growth, profitability, balance sheet, competitive moat, and management quality.',
    longDescription:
      'A source-checked fundamental-analysis skill from AI Trading Claude that produces a structured company research report. Its upstream documentation explicitly frames outputs as educational and research material; agents should validate the sources and treat every score as a research input rather than financial advice or an automated trading signal.',
    repo: 'zubair-trabzada/ai-trading-claude',
    repository: 'https://github.com/zubair-trabzada/ai-trading-claude/tree/main/skills/trade-fundamental',
    installCommand: 'npx -y skills add zubair-trabzada/ai-trading-claude --skill trade-fundamental',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'fundamental-analysis', 'valuation', 'balance-sheet', 'competitive-moat'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh'],
    stars: 218,
    quality: 78,
    reviewScore: 73,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-04-07T00:00:00.000Z',
    reviewIssues: ['Repository freshness is limited; outputs are educational research only and must not be used as financial advice.'],
    reviewSuggestions: ['Cite current primary sources for material claims.', 'Ask a human reviewer to challenge the analysis before action.'],
  }),
  snapshotSkill({
    slug: 'portfolio-analytics',
    name: 'Portfolio Analytics',
    description: 'Measure portfolio returns, risk, drawdowns, benchmarks, rolling metrics, and strategy performance from approved data.',
    longDescription:
      'A source-checked portfolio research skill from Agipro Labs for analyzing equity curves and trade logs with return, drawdown, and risk-adjusted metrics. It produces a useful performance-analysis artifact, but input files can be sensitive and results must be validated for data completeness, fees, survivorship bias, and reporting assumptions before any investor communication.',
    repo: 'agiprolabs/claude-trading-skills',
    repository: 'https://github.com/agiprolabs/claude-trading-skills/tree/main/skills/portfolio-analytics',
    installCommand: 'npx -y skills add agiprolabs/claude-trading-skills --skill portfolio-analytics',
    category: 'Finance',
    tags: ['agent-skill', 'finance', 'portfolio', 'performance-analysis', 'drawdown', 'backtesting'],
    frameworks: ['Claude Code', 'Codex', 'skills.sh', 'QuantStats'],
    stars: 267,
    quality: 79,
    reviewScore: 74,
    verified: false,
    license: 'MIT',
    lastPushedAt: '2026-06-24T00:00:00.000Z',
    reviewIssues: ['Portfolio and trade-log data can be sensitive; validate assumptions, fees, and benchmark handling before reporting results.'],
    reviewSuggestions: ['Use a sanitized dataset for the first run.', 'Retain the inputs and calculation settings with the report.'],
  }),
]
