import 'server-only'
import previews from './skill-previews.json'
import bindings from './skill-preview-bindings.json'
import automatic from './skill-previews-auto.json'
import { getShowcaseCase, getShowcaseImageSrc } from './showcase'
import type { SkillPreviewCardData, SkillSourcePreview } from './skill-preview-shared'

const registry = new Map((previews as SkillSourcePreview[]).map(preview => [preview.skillSlug, preview]))
// Reuse licensed Gallery assets through explicit, source-checked relationships.
// A repo-wide or fuzzy name match would incorrectly attach sibling skill outputs.
for (const binding of bindings) {
  if (registry.has(binding.skillSlug)) throw new Error(`Duplicate preview binding: ${binding.skillSlug}`)
  const cases = binding.caseSlugs.map(slug => {
    const item = getShowcaseCase(slug)
    if (!item) throw new Error(`Missing bound Gallery case: ${slug}`)
    return item
  })
  const first = cases[0]
  const upstream = binding.relationship === 'upstream-template'
  registry.set(binding.skillSlug, {
    skillSlug: binding.skillSlug, repository: new URL(first.sourceUrl).pathname.split('/').slice(1, 3).join('/'),
    revision: first.sourceRevision, sourceUrl: first.sourceUrl, license: first.license, licenseUrl: first.licenseUrl,
    bindingUrl: `https://github.com/${binding.repository}/blob/${binding.revision}/${binding.sourcePath}`,
    format: upstream ? { en: 'Upstream HTML slide template', zh: '上游 HTML 幻灯片模板' } : { en: 'Author design preview', zh: '作者设计预览' },
    note: upstream ? {
      en: 'This skill explicitly references this upstream template. These are the template author’s previews, not a new output generated by this skill or an editable PowerPoint file.',
      zh: '此技能明确引用了这套上游模板。这里展示模板作者的预览，不是此技能新生成的成品，也不是可编辑 PowerPoint 文件。',
    } : { en: 'The author’s published preview for this specific design template. Sample content and interface behavior have not been independently tested.', zh: '作者为这套具体设计模板发布的预览。示例内容与界面功能未经本站独立测试。' },
    media: cases.flatMap(item => item.media.map(media => ({
      ...media, cardSrc: getShowcaseImageSrc(media.src, 'card'), previewSrc: getShowcaseImageSrc(media.src, 'preview'),
      kind: upstream ? 'template' as const : 'example' as const, title: item.title, sourceUrl: item.sourceUrl,
    }))),
  })
}
// The automatic collector uses exact source identities and immutable assets.
// Explicitly curated previews and bindings always take precedence.
for (const preview of automatic as SkillSourcePreview[]) {
  if (!registry.has(preview.skillSlug)) registry.set(preview.skillSlug, preview)
}
export const SKILL_SOURCE_PREVIEWS = [...registry.values()]
// An interface or an input image alone is not an output example.
export const SOURCE_EXAMPLE_SKILL_SLUGS = [...registry.values()]
  .filter(preview => preview.media.some(image => ['example', 'template', 'style'].includes(image.kind)))
  .map(preview => preview.skillSlug)

export const getSkillSourcePreview = (slug: string) => registry.get(slug) || null
export function getSkillPreviewCardData(slug: string): SkillPreviewCardData | null {
  const preview = getSkillSourcePreview(slug)
  return preview ? { media: preview.media[0], imageCount: preview.media.length, format: preview.format } : null
}

// Link to author galleries when redistribution permission is not established.
// These are references, not local examples, and never affect example counts.
export const SOURCE_GALLERY_LINKS: Record<string, string> = {
  'adobe-research-custom-diffusion': 'https://nupurkmr9.github.io/custom-diffusion/results.html',
  'foundationvision-var': 'https://github.com/FoundationVision/VAR/blob/78b95394fc5896192e3a003e4b295f8ea743c48f/README.md',
}
