export const DEFAULT_AI_GATEWAY_MODEL =
  process.env.OPENAGENTSKILL_AI_MODEL || 'deepseek/deepseek-v4-flash'

export const SUBMISSION_REVIEW_MODEL =
  process.env.OPENAGENTSKILL_REVIEW_MODEL || DEFAULT_AI_GATEWAY_MODEL

export const INDEXER_REVIEW_MODEL =
  process.env.OPENAGENTSKILL_INDEXER_MODEL || DEFAULT_AI_GATEWAY_MODEL

export const BLOG_GENERATION_MODEL =
  process.env.OPENAGENTSKILL_BLOG_MODEL || DEFAULT_AI_GATEWAY_MODEL
