import type { Locale } from './config'

const en = {
  pricing: 'Price', all: 'All prices', free: 'Free to get', paid: 'Paid', freemium: 'Free + paid editions', unknown: 'Price unconfirmed',
  title: 'Price & running costs', acquisition: 'Get the skill', running: 'Run it', license: 'License',
  model: 'Bring your own agent or model plan. Usage charges may apply.',
  'optional-services': 'Model services are optional and billed separately. Local workflows still use your own compute and agent.',
  runtimeUnknown: 'Requirements have not been confirmed. Check the source for agent, API and service charges.',
  caveat: 'Free to get does not mean free to run. Price labels are not safety ratings.',
  source: 'Pricing source', checked: 'Checked', buy: 'View official offer',
  external: 'Purchase on the seller’s website. Check delivery, updates, support and refund terms there. OpenAgentSkill does not process this payment.',
  contribute: 'Submit pricing information', empty: 'No matching offers with confirmed pricing yet. Unconfirmed does not mean paid.',
  'one-time': 'one-time', monthly: '/ month', yearly: '/ year', 'usage-based': 'usage-based', contact: 'Contact seller',
  unknownNote: 'We have not confirmed a price for this skill. Existing source and install links remain available.',
}
type Copy = Record<keyof typeof en, string>
const zh: Copy = {
  pricing:'价格',all:'全部价格',free:'免费获取',paid:'付费',freemium:'免费＋付费版本',unknown:'价格未确认',
  title:'获取价格与运行成本',acquisition:'获取 Skill',running:'运行 Skill',license:'许可证',
  model:'需自备 Agent 或模型额度，使用时可能产生费用。',
  'optional-services':'模型服务可选，费用单独计算。本地工作流仍需使用自己的算力和 Agent。',
  runtimeUnknown:'尚未确认运行要求，请查看来源中的 Agent、API 和服务费用。',
  caveat:'免费获取不代表免费运行，价格标签不代表安全评级。',source:'价格来源',checked:'核对日期',buy:'查看官方购买方案',
  external:'将在卖方网站购买，请核对交付内容、更新、支持和退款条款。OpenAgentSkill 不处理本次付款。',
  contribute:'提交价格信息',empty:'暂时没有符合筛选条件且价格已确认的方案。未确认不等于付费。',
  'one-time':'一次性',monthly:'/ 月',yearly:'/ 年','usage-based':'按量计费',contact:'联系卖方',
  unknownNote:'我们尚未确认此 Skill 的价格，现有来源与安装入口仍可使用。',
}
const ja: Copy = {pricing:'価格',all:'すべての価格',free:'無料で入手',paid:'有料',freemium:'無料・有料版',unknown:'価格未確認',title:'価格と実行コスト',acquisition:'Skill の入手',running:'実行',license:'ライセンス',model:'ご自身の Agent・モデルプランが必要です。利用料金が発生する場合があります。','optional-services':'モデルサービスは任意で、別途課金されます。ローカル実行にも計算資源と Agent が必要です。',runtimeUnknown:'実行要件は未確認です。Agent・API・サービス料金を提供元で確認してください。',caveat:'無料で入手できても実行が無料とは限りません。価格は安全評価ではありません。',source:'価格の出典',checked:'確認日',buy:'公式プランを見る',external:'販売元のサイトで購入します。納品、更新、サポート、返金条件を確認してください。当サイトは決済しません。',contribute:'価格情報を送る',empty:'条件に合う価格確認済みのプランはありません。未確認は有料を意味しません。','one-time':'買い切り',monthly:'/ 月',yearly:'/ 年','usage-based':'従量課金',contact:'販売元に連絡',unknownNote:'価格は未確認です。既存のソースとインストールリンクは利用できます。'}
const ko: Copy = {pricing:'가격',all:'모든 가격',free:'무료로 받기',paid:'유료',freemium:'무료·유료 버전',unknown:'가격 미확인',title:'가격 및 실행 비용',acquisition:'Skill 받기',running:'실행',license:'라이선스',model:'자신의 Agent 또는 모델 요금제가 필요하며 사용 요금이 발생할 수 있습니다.','optional-services':'모델 서비스는 선택 사항이며 별도 과금됩니다. 로컬 실행에도 컴퓨팅 자원과 Agent가 필요합니다.',runtimeUnknown:'실행 요구 사항이 확인되지 않았습니다. 제공처에서 Agent, API 및 서비스 요금을 확인하세요.',caveat:'무료 다운로드가 무료 실행을 뜻하지 않습니다. 가격은 안전 등급이 아닙니다.',source:'가격 출처',checked:'확인일',buy:'공식 구매 옵션',external:'판매자 사이트에서 구매합니다. 제공 내용, 업데이트, 지원 및 환불 조건을 확인하세요. 본 사이트는 결제를 처리하지 않습니다.',contribute:'가격 정보 제출',empty:'조건에 맞는 가격 확인 상품이 없습니다. 미확인은 유료를 의미하지 않습니다.','one-time':'일회성',monthly:'/ 월',yearly:'/ 년','usage-based':'사용량 과금',contact:'판매자 문의',unknownNote:'가격을 아직 확인하지 못했습니다. 기존 소스 및 설치 링크는 계속 이용할 수 있습니다.'}
const es: Copy = {pricing:'Precio',all:'Todos los precios',free:'Obtención gratuita',paid:'De pago',freemium:'Versiones gratuitas y de pago',unknown:'Precio sin confirmar',title:'Precio y costes de ejecución',acquisition:'Obtener el skill',running:'Ejecutarlo',license:'Licencia',model:'Usa tu propio plan de agente o modelo. Puede haber cargos por uso.','optional-services':'Los servicios de modelos son opcionales y se cobran aparte. Los flujos locales requieren tus recursos y agente.',runtimeUnknown:'Requisitos sin confirmar. Consulta los costes del agente, API y servicios en la fuente.',caveat:'Obtener gratis no significa ejecutar gratis. El precio no es una evaluación de seguridad.',source:'Fuente del precio',checked:'Comprobado',buy:'Ver oferta oficial',external:'Compra en la web del vendedor. Consulta entrega, actualizaciones, soporte y reembolsos. OpenAgentSkill no procesa el pago.',contribute:'Enviar información de precio',empty:'No hay ofertas coincidentes con precio confirmado. Sin confirmar no significa de pago.','one-time':'pago único',monthly:'/ mes',yearly:'/ año','usage-based':'por uso',contact:'Contactar al vendedor',unknownNote:'No hemos confirmado el precio. Los enlaces existentes al código y a la instalación siguen disponibles.'}
const de: Copy = {pricing:'Preis',all:'Alle Preise',free:'Kostenlos erhältlich',paid:'Kostenpflichtig',freemium:'Kostenlose und kostenpflichtige Versionen',unknown:'Preis unbestätigt',title:'Preis und Betriebskosten',acquisition:'Skill beziehen',running:'Ausführen',license:'Lizenz',model:'Eigenen Agenten- oder Modelltarif nutzen. Nutzungsgebühren können anfallen.','optional-services':'Modelldienste sind optional und werden separat berechnet. Lokale Abläufe benötigen eigene Rechenleistung und Agenten.',runtimeUnknown:'Anforderungen unbestätigt. Agenten-, API- und Dienstkosten an der Quelle prüfen.',caveat:'Kostenloser Bezug bedeutet nicht kostenlosen Betrieb. Preise sind keine Sicherheitsbewertung.',source:'Preisquelle',checked:'Geprüft',buy:'Offizielles Angebot ansehen',external:'Kauf auf der Website des Verkäufers. Lieferung, Updates, Support und Erstattung prüfen. OpenAgentSkill wickelt keine Zahlung ab.',contribute:'Preisinformation einreichen',empty:'Keine passenden Angebote mit bestätigtem Preis. Unbestätigt bedeutet nicht kostenpflichtig.','one-time':'einmalig',monthly:'/ Monat',yearly:'/ Jahr','usage-based':'nach Nutzung',contact:'Verkäufer kontaktieren',unknownNote:'Der Preis ist noch nicht bestätigt. Vorhandene Quell- und Installationslinks bleiben verfügbar.'}
const fr: Copy = {pricing:'Prix',all:'Tous les prix',free:'Obtention gratuite',paid:'Payant',freemium:'Versions gratuites et payantes',unknown:'Prix non confirmé',title:'Prix et coûts d’utilisation',acquisition:'Obtenir le skill',running:'L’utiliser',license:'Licence',model:'Utilisez votre propre abonnement agent ou modèle. Des frais peuvent s’appliquer.','optional-services':'Les services de modèles sont facultatifs et facturés séparément. Les flux locaux nécessitent vos ressources et votre agent.',runtimeUnknown:'Prérequis non confirmés. Consultez les frais d’agent, d’API et de services à la source.',caveat:'Gratuit à obtenir ne signifie pas gratuit à utiliser. Le prix ne constitue pas une évaluation de sécurité.',source:'Source du prix',checked:'Vérifié le',buy:'Voir l’offre officielle',external:'Achat sur le site du vendeur. Vérifiez livraison, mises à jour, assistance et remboursements. OpenAgentSkill ne traite pas ce paiement.',contribute:'Soumettre un prix',empty:'Aucune offre correspondante au prix confirmé. Non confirmé ne signifie pas payant.','one-time':'paiement unique',monthly:'/ mois',yearly:'/ an','usage-based':'à l’usage',contact:'Contacter le vendeur',unknownNote:'Le prix n’est pas confirmé. Les liens existants vers les sources et l’installation restent disponibles.'}
const id: Copy = {pricing:'Harga',all:'Semua harga',free:'Gratis diperoleh',paid:'Berbayar',freemium:'Versi gratis + berbayar',unknown:'Harga belum dikonfirmasi',title:'Harga dan biaya penggunaan',acquisition:'Dapatkan skill',running:'Jalankan',license:'Lisensi',model:'Gunakan paket agen atau model sendiri. Biaya penggunaan mungkin berlaku.','optional-services':'Layanan model bersifat opsional dan ditagih terpisah. Alur lokal tetap memerlukan komputasi dan agen Anda.',runtimeUnknown:'Persyaratan belum dikonfirmasi. Periksa biaya agen, API, dan layanan di sumbernya.',caveat:'Gratis diperoleh bukan berarti gratis dijalankan. Harga bukan penilaian keamanan.',source:'Sumber harga',checked:'Diperiksa',buy:'Lihat penawaran resmi',external:'Beli di situs penjual. Periksa pengiriman, pembaruan, dukungan, dan pengembalian dana. OpenAgentSkill tidak memproses pembayaran ini.',contribute:'Kirim informasi harga',empty:'Belum ada penawaran sesuai dengan harga terkonfirmasi. Belum dikonfirmasi bukan berarti berbayar.','one-time':'sekali bayar',monthly:'/ bulan',yearly:'/ tahun','usage-based':'berdasarkan penggunaan',contact:'Hubungi penjual',unknownNote:'Harga belum dikonfirmasi. Tautan sumber dan instalasi yang ada tetap tersedia.'}
export function commerceCopy(locale: Locale): Copy { return {en, zh, ja, ko, es, de, fr, id}[locale] || en }
