import type { Locale } from './config'

const en = {
  label: 'Mysticism', title: 'Mysticism & reflection', eyebrow: 'Traditional culture · Entertainment',
  intro: 'Explore open-source skills for traditional divination, chart reading, everyday rituals and self-reflection. Choose a practice, read its limits, then decide what to use.',
  groups: ['Divination & questions', 'Charts & cycles', 'Self-reflection', 'Space & imagery'],
  groupDescriptions: ['One question, a named method, and explicit uncertainty.', 'Calculation conventions first; symbolic interpretation second.', 'Reflection and habit-building, including non-divination companions.', 'Visible observations are not evidence of character, health or destiny.'],
  details: 'View skill', source: 'GitHub source', demo: 'Try on 6yao.ai', back: 'All skills', collection: 'Skills in this collection',
  noticeTitle: 'Culture, not certainty.',
  notice: 'These practices are not scientifically validated predictions and do not replace medical, legal, financial or mental-health advice. Never infer sensitive traits, intelligence or trustworthiness from a face or hand.',
  disclosure: 'Creator disclosure: this collection features Leon-Drq’s 6yao projects, published through the site-owner channel. Inclusion is not AI review, a runtime test or a safety endorsement. Check the current status on each detail page.',
  privacy: 'Birth details, photos and relationship histories are personal data. Share only with permission. The online demos are external services and may require an account or payment; the MIT license applies to the repositories, not to free hosted access.',
  summaries: 'Skill names and editorial summaries below are in English.',
}
type Copy = typeof en
const copy: Record<Locale, Copy> = {
  en,
  zh: { label: '玄学', title: '玄学与自我探索', eyebrow: '传统文化 · 娱乐体验', intro: '探索传统起卦、命盘解读、日常仪式与自我观察的开源 Skill。按用途选择，先了解边界，再决定如何使用。', groups: ['起卦与问事', '命盘与周期', '自我探索', '空间与影像'], groupDescriptions: ['一个具体问题，一套明确方法，保留不确定性。', '先核对计算与历法，再阅读传统象征解释。', '自我观察与习惯养成，也包含非占卜的配套工具。', '可见外观不能证明性格、健康或命运。'], details: '查看技能', source: 'GitHub 源码', demo: '在 6yao.ai 体验', back: '全部技能', collection: '专题技能', noticeTitle: '了解文化，不把象征当结论。', notice: '这些方法不具有经科学验证的预测能力，不能替代医疗、法律、财务或心理健康专业意见。不得根据面貌或掌纹推断敏感属性、智力或可信度。', disclosure: '创作者披露：本专题收录 Leon-Drq 的 6yao 项目，使用站点所有者通道发布。收录不等于 AI 审核通过、运行测试或安全背书；当前状态请查看各技能详情页。', privacy: '出生资料、照片与关系经历属于个人数据，请仅在获得许可后分享。在线体验为外部服务，可能需要账户或付费；MIT 许可证适用于仓库，不代表托管服务免费。', summaries: '' },
  ja: { ...en, label: '占術・文化', title: '占術と自己省察', eyebrow: '伝統文化 · エンターテインメント', intro: '伝統的な占術、命盤、日々の儀式、自己省察のオープンソーススキル。用途と限界を確認して選べます。', groups: ['占術と問い', '命盤と周期', '自己省察', '空間と画像'], groupDescriptions: ['一つの問いと明確な方法。不確実性を残します。', '計算条件と象徴的な解釈を分けます。', '占術ではない習慣づくりのツールも含みます。', '外見は性格、健康、運命の根拠にはなりません。'], details: 'スキルを見る', source: 'GitHub ソース', demo: '6yao.ai で試す', back: 'すべてのスキル', collection: '収録スキル', noticeTitle: '文化として、確実な予測ではなく。', notice: '科学的に検証された予測ではありません。医療・法律・金融・心理の専門的助言に代わるものではなく、顔や手から機微な属性、知能、信頼性を推測してはいけません。', disclosure: '制作者の開示：Leon-Drq の 6yao プロジェクトをサイト所有者の権限で掲載しています。AI 審査、実行テスト、安全性の保証を意味しません。各詳細ページで現在の状態を確認してください。', privacy: '出生情報、写真、関係の履歴は個人情報です。同意を得て共有してください。外部デモはアカウントや料金が必要な場合があります。MIT はリポジトリに適用され、サービスの無料利用を意味しません。', summaries: '以下のスキル名と紹介文は英語です。' },
  ko: { ...en, label: '점술·문화', title: '점술과 자기 성찰', eyebrow: '전통문화 · 엔터테인먼트', intro: '전통 점술, 명식, 일상 의식과 자기 성찰을 위한 오픈소스 스킬입니다. 용도와 한계를 확인하고 선택하세요.', groups: ['점술과 질문', '명식과 주기', '자기 성찰', '공간과 이미지'], groupDescriptions: ['구체적인 질문과 방법, 명시적인 불확실성.', '계산 조건과 상징적 해석을 구분합니다.', '점술이 아닌 습관 형성 도구도 포함합니다.', '외모는 성격, 건강, 운명의 증거가 아닙니다.'], details: '스킬 보기', source: 'GitHub 소스', demo: '6yao.ai에서 체험', back: '모든 스킬', collection: '모음의 스킬', noticeTitle: '문화이지, 확실한 예측은 아닙니다.', notice: '과학적으로 검증된 예측이 아니며 의료·법률·재무·정신건강 조언을 대체하지 않습니다. 얼굴이나 손으로 민감한 특성, 지능, 신뢰성을 추론하지 마세요.', disclosure: '제작자 고지: Leon-Drq의 6yao 프로젝트를 사이트 소유자 채널로 게시했습니다. AI 심사, 실행 테스트 또는 안전 보증이 아닙니다. 현재 상태는 각 상세 페이지에서 확인하세요.', privacy: '출생 정보, 사진과 관계 기록은 개인정보입니다. 허락을 받고 공유하세요. 외부 체험은 계정이나 결제가 필요할 수 있습니다. MIT 라이선스는 저장소에 적용되며 서비스 무료 이용을 뜻하지 않습니다.', summaries: '아래 스킬 이름과 소개는 영어로 제공됩니다.' },
  es: { ...en, label: 'Misticismo', title: 'Misticismo y reflexión', eyebrow: 'Cultura tradicional · Entretenimiento', intro: 'Skills de código abierto para adivinación tradicional, cartas, rituales cotidianos y reflexión. Consulta sus límites antes de usarlas.', groups: ['Adivinación y preguntas', 'Cartas y ciclos', 'Reflexión personal', 'Espacio e imágenes'], groupDescriptions: ['Una pregunta y un método, con incertidumbre explícita.', 'Separar cálculos e interpretación simbólica.', 'Incluye herramientas de hábitos sin adivinación.', 'La apariencia no demuestra carácter, salud ni destino.'], details: 'Ver skill', source: 'Código en GitHub', demo: 'Probar en 6yao.ai', back: 'Todas las skills', collection: 'Skills de la colección', noticeTitle: 'Cultura, no certezas.', notice: 'No son predicciones científicamente validadas ni sustituyen asesoramiento médico, legal, financiero o de salud mental. No inferir rasgos sensibles, inteligencia o fiabilidad a partir de rostros o manos.', disclosure: 'Divulgación: proyectos 6yao de Leon-Drq publicados por el propietario del sitio. Su inclusión no implica revisión de IA, pruebas de ejecución ni garantía de seguridad. Consulta el estado en cada ficha.', privacy: 'Los datos de nacimiento, fotos e historias de relaciones son personales. Compártelos solo con permiso. Las demos externas pueden requerir cuenta o pago. MIT cubre los repositorios, no acceso gratuito al servicio.', summaries: 'Los nombres y resúmenes de las skills se muestran en inglés.' },
  de: { ...en, label: 'Mystik', title: 'Mystik und Selbstreflexion', eyebrow: 'Traditionelle Kultur · Unterhaltung', intro: 'Open-Source-Skills für traditionelle Orakel, Horoskope, Alltagsrituale und Selbstreflexion. Vor der Nutzung die Grenzen prüfen.', groups: ['Orakel und Fragen', 'Horoskope und Zyklen', 'Selbstreflexion', 'Raum und Bilder'], groupDescriptions: ['Eine konkrete Frage, eine Methode, klare Unsicherheit.', 'Berechnung und symbolische Deutung trennen.', 'Auch Gewohnheitshilfen ohne Wahrsagung.', 'Aussehen belegt weder Charakter noch Gesundheit oder Schicksal.'], details: 'Skill ansehen', source: 'GitHub-Quellcode', demo: 'Auf 6yao.ai testen', back: 'Alle Skills', collection: 'Skills dieser Sammlung', noticeTitle: 'Kultur, keine Gewissheit.', notice: 'Keine wissenschaftlich bestätigten Vorhersagen und kein Ersatz für medizinische, rechtliche, finanzielle oder psychologische Beratung. Aus Gesicht oder Hand keine sensiblen Merkmale, Intelligenz oder Vertrauenswürdigkeit ableiten.', disclosure: 'Offenlegung: 6yao-Projekte von Leon-Drq, über den Website-Eigentümer veröffentlicht. Aufnahme bedeutet weder KI-Prüfung noch Laufzeittest oder Sicherheitsgarantie. Den aktuellen Status zeigt die jeweilige Detailseite.', privacy: 'Geburtsdaten, Fotos und Beziehungsgeschichten sind personenbezogen. Nur mit Erlaubnis teilen. Externe Demos können Konto oder Bezahlung erfordern. MIT gilt für Repositories, nicht für kostenlosen Servicezugang.', summaries: 'Skill-Namen und Zusammenfassungen unten sind auf Englisch.' },
  fr: { ...en, label: 'Mysticisme', title: 'Mysticisme et réflexion', eyebrow: 'Culture traditionnelle · Divertissement', intro: 'Des skills open source pour la divination traditionnelle, les thèmes, les rituels et la réflexion personnelle. Consultez leurs limites avant utilisation.', groups: ['Divination et questions', 'Thèmes et cycles', 'Réflexion personnelle', 'Espace et images'], groupDescriptions: ['Une question, une méthode et une incertitude explicite.', 'Distinguer calculs et interprétation symbolique.', 'Inclut des outils d’habitudes sans divination.', 'L’apparence ne prouve ni caractère, ni santé, ni destin.'], details: 'Voir la skill', source: 'Source GitHub', demo: 'Essayer sur 6yao.ai', back: 'Toutes les skills', collection: 'Skills de la collection', noticeTitle: 'De la culture, pas des certitudes.', notice: 'Ces pratiques ne sont pas des prédictions scientifiquement validées et ne remplacent pas les conseils médicaux, juridiques, financiers ou psychologiques. Ne déduisez pas de traits sensibles, d’intelligence ou de fiabilité d’un visage ou d’une main.', disclosure: 'Transparence : projets 6yao de Leon-Drq publiés par le propriétaire du site. Leur présence ne signifie ni validation par IA, ni test d’exécution, ni garantie de sécurité. Consultez chaque fiche pour le statut actuel.', privacy: 'Dates de naissance, photos et histoires relationnelles sont des données personnelles. Partagez-les avec autorisation. Les démos externes peuvent nécessiter un compte ou un paiement. MIT couvre les dépôts, pas un accès gratuit au service.', summaries: 'Les noms et résumés des skills ci-dessous sont en anglais.' },
  id: { ...en, label: 'Mistisisme', title: 'Mistisisme dan refleksi', eyebrow: 'Budaya tradisional · Hiburan', intro: 'Skill sumber terbuka untuk ramalan tradisional, bagan, ritual harian dan refleksi diri. Pahami batasannya sebelum memilih.', groups: ['Ramalan dan pertanyaan', 'Bagan dan siklus', 'Refleksi diri', 'Ruang dan gambar'], groupDescriptions: ['Satu pertanyaan, metode jelas, ketidakpastian terbuka.', 'Pisahkan perhitungan dari interpretasi simbolis.', 'Termasuk alat kebiasaan tanpa ramalan.', 'Penampilan bukan bukti karakter, kesehatan atau nasib.'], details: 'Lihat skill', source: 'Sumber GitHub', demo: 'Coba di 6yao.ai', back: 'Semua skill', collection: 'Skill dalam koleksi', noticeTitle: 'Budaya, bukan kepastian.', notice: 'Bukan prediksi yang terbukti secara ilmiah dan bukan pengganti nasihat medis, hukum, keuangan atau kesehatan mental. Jangan menyimpulkan sifat sensitif, kecerdasan atau kepercayaan dari wajah atau tangan.', disclosure: 'Pengungkapan: proyek 6yao milik Leon-Drq diterbitkan melalui jalur pemilik situs. Pencantuman bukan tinjauan AI, uji eksekusi atau jaminan keamanan. Periksa status terkini di halaman detail.', privacy: 'Data lahir, foto dan riwayat hubungan adalah data pribadi. Bagikan hanya dengan izin. Demo eksternal mungkin memerlukan akun atau pembayaran. MIT berlaku untuk repositori, bukan akses layanan gratis.', summaries: 'Nama dan ringkasan skill di bawah tersedia dalam bahasa Inggris.' },
}
export const getMysticismCopy = (locale: Locale): Copy => copy[locale]
