import type { Locale } from './config'
import { directoryLabel } from './directory-copy'
import type { RankingDefinition, RankingKind } from '@/lib/rankings'

const locales: Locale[] = ['en', 'zh', 'ja', 'ko', 'es', 'de', 'fr', 'id']
const labels = {
  eyebrow: ['Skill rankings','技能排行榜','スキルランキング','스킬 순위','Rankings de skills','Skill-Ranglisten','Classements de skills','Peringkat skill'],
  report: ['Agent proven','Agent 证据报告','Agent 結果レポート','Agent 결과 보고서','Informe de resultados agent','Agent-Ergebnisbericht','Rapport de résultats agent','Laporan hasil agent'],
  choose: ['Choose a ranking','选择榜单','ランキングを選択','순위 선택','Elige un ranking','Rangliste wählen','Choisir un classement','Pilih peringkat'],
  go: ['View list','查看榜单','一覧を見る','목록 보기','Ver lista','Liste ansehen','Voir la liste','Lihat daftar'],
  compare: ['Compare top 4','对比前 4 项','上位4件を比較','상위 4개 비교','Comparar los 4 primeros','Top 4 vergleichen','Comparer le top 4','Bandingkan 4 teratas'],
  share: ['Share ranking','分享榜单','ランキングを共有','순위 공유','Compartir ranking','Rangliste teilen','Partager le classement','Bagikan peringkat'],
  history: ['30-day snapshot data','近 30 天快照数据','30日間の保存データ','30일 스냅샷 데이터','Datos guardados de 30 días','30-Tage-Snapshot-Daten','Données sauvegardées sur 30 jours','Data snapshot 30 hari'],
  evidence: ['Ranking signals','排名依据','ランキングの根拠','순위 근거','Señales del ranking','Ranking-Signale','Signaux du classement','Sinyal peringkat'],
  method: ['How this list works','榜单如何排序','並び順について','정렬 방식','Cómo se ordena esta lista','So wird diese Liste sortiert','Comment cette liste est classée','Cara daftar ini diurutkan'],
  scope: ['Shown: {shown} · Candidates: {count}','展示 {shown} 项 · 候选 {count} 项','表示 {shown} 件 · 候補 {count} 件','표시 {shown}개 · 후보 {count}개','Mostrados: {shown} · Candidatos: {count}','Angezeigt: {shown} · Kandidaten: {count}','Affichés : {shown} · Candidats : {count}','Ditampilkan: {shown} · Kandidat: {count}'],
  notice: ['A shortlist from up to 480 directory candidates, not the entire registry. Stars belong to repositories. Signals are not safety guarantees or runtime verification.','基于最多 480 个目录候选生成，并非全站排名。Star 属于仓库；评分不代表安全保证或运行验证。','最大480件の候補から作成した一覧です。全登録の順位ではありません。スターはリポジトリの値で、安全性や動作の保証ではありません。','최대 480개 후보의 목록이며 전체 등록 순위가 아닙니다. 스타는 저장소 수치이며 신호는 안전이나 실행 검증을 보장하지 않습니다.','Selección de hasta 480 candidatos, no de todo el registro. Las estrellas son del repositorio. Las señales no garantizan seguridad ni ejecución.','Auswahl aus bis zu 480 Kandidaten, nicht dem gesamten Register. Sterne gehören zum Repository. Signale garantieren weder Sicherheit noch Laufzeitprüfung.','Sélection parmi au plus 480 candidats, pas tout le registre. Les étoiles sont celles du dépôt. Les signaux ne garantissent ni sécurité ni validation en exécution.','Pilihan dari hingga 480 kandidat, bukan seluruh registri. Bintang milik repositori. Sinyal bukan jaminan keamanan atau verifikasi eksekusi.'],
  unavailable: ['Ranking data is temporarily unavailable. Browse the directory or try again later.','榜单数据暂不可用，可先浏览技能目录或稍后重试。','ランキングを取得できません。ディレクトリをご覧になるか、後で再試行してください。','순위 데이터를 사용할 수 없습니다. 디렉터리를 보거나 나중에 다시 시도하세요.','Datos no disponibles temporalmente. Explora el directorio o vuelve más tarde.','Ranking-Daten vorübergehend nicht verfügbar. Nutze das Verzeichnis oder versuche es später erneut.','Classement temporairement indisponible. Consultez le répertoire ou réessayez plus tard.','Data peringkat sementara tidak tersedia. Jelajahi direktori atau coba lagi nanti.'],
  empty: ['No matching skills in the current candidate set. Explore another ranking or browse all skills.','当前候选集中暂无符合条件的技能。可切换榜单或浏览全部技能。','現在の候補に該当するスキルはありません。別のランキングや全スキルをご覧ください。','현재 후보에 맞는 스킬이 없습니다. 다른 순위나 전체 스킬을 확인하세요.','Sin coincidencias en los candidatos actuales. Explora otro ranking o todos los skills.','Keine passenden Skills in dieser Auswahl. Wähle eine andere Rangliste oder alle Skills.','Aucun skill correspondant parmi les candidats actuels. Explorez un autre classement ou tous les skills.','Tidak ada skill yang cocok dalam kandidat saat ini. Pilih peringkat lain atau semua skill.'],
  saved: ['Saved directory data is shown because current data is unavailable. Dates and metrics may be out of date.','当前数据不可用，正在展示已保存的目录数据；日期和指标可能已过期。','現在のデータを取得できないため保存済みデータを表示しています。日付や指標は古い可能性があります。','현재 데이터 대신 저장된 디렉터리를 표시합니다. 날짜와 지표가 오래되었을 수 있습니다.','Se muestran datos guardados. Las fechas y métricas pueden estar desactualizadas.','Gespeicherte Verzeichnisdaten werden angezeigt. Daten und Kennzahlen können veraltet sein.','Données sauvegardées affichées. Les dates et mesures peuvent être obsolètes.','Data direktori tersimpan ditampilkan. Tanggal dan metrik mungkin sudah usang.'],
  indexed: ['Indexed','收录日期','登録日','등록일','Indexado','Indexiert','Indexé','Diindeks'],
  registryUpdated: ['Directory updated','目录更新时间','登録情報の更新','디렉터리 갱신','Directorio actualizado','Verzeichnis aktualisiert','Répertoire mis à jour','Direktori diperbarui'],
  pushed: ['Repository push','仓库更新','リポジトリ更新','저장소 업데이트','Actualización del repositorio','Repository-Update','Mise à jour du dépôt','Pembaruan repositori'],
  unknown: ['Not recorded','未记录','記録なし','기록 없음','Sin registro','Nicht erfasst','Non enregistré','Tidak tercatat'],
  quality: ['Quality','质量','品質','품질','Calidad','Qualität','Qualité','Kualitas'],
  popularity: ['Popularity','人气','人気','인기도','Popularidad','Popularität','Popularité','Popularitas'],
  freshness: ['Freshness','新鲜度','鮮度','최신성','Actualidad','Aktualität','Actualité','Kebaruan'],
  agentEvidence: ['Agent evidence','Agent 结果证据','Agent の結果証拠','Agent 결과 근거','Evidencia del agente','Agent-Ergebnisbelege','Preuves de résultats agent','Bukti hasil agent'],
  evidenceConfidence: ['Evidence confidence','证据置信度','証拠の確かさ','근거 신뢰도','Confianza de evidencia','Evidenzkonfidenz','Confiance des preuves','Keyakinan bukti'],
  installReadiness: ['Install readiness','安装准备度','インストール準備度','설치 준비도','Preparación de instalación','Installationsbereitschaft','Préparation à l’installation','Kesiapan instalasi'],
  fit: ['Task fit','任务匹配度','タスク適合度','작업 적합도','Adecuación a la tarea','Aufgabenpassung','Adéquation à la tâche','Kesesuaian tugas'],
  signalsNote: ['Signals use a 0–100 scale. They explain the shortlist; the ordering follows this list’s method, not any one score.','各项信号采用 0–100 分，仅辅助判断；排序遵循本榜单规则，不由单项分数决定。','各指標は0～100です。並び順は単一指標ではなく、この一覧の基準に従います。','신호는 0~100 척도입니다. 순서는 단일 점수가 아닌 이 목록의 방식에 따릅니다.','Señales de 0 a 100. El orden sigue el método de la lista, no una sola puntuación.','Signale auf einer Skala von 0–100. Die Reihenfolge folgt der Listenmethode, nicht einem Einzelwert.','Signaux sur une échelle de 0 à 100. L’ordre suit la méthode de la liste, pas un score isolé.','Sinyal memakai skala 0–100. Urutan mengikuti metode daftar, bukan satu skor saja.'],
  intro: ['Explore {name}. Check each skill’s source and review notes before use.','探索「{name}」中的技能，使用前请查看详情页的来源与审核说明。','「{name}」のスキルを探す。使用前にソースとレビューを確認してください。','{name} 스킬을 탐색하세요. 사용 전 출처와 검토 내용을 확인하세요.','Explora {name}. Revisa la fuente y las notas antes de usar cada skill.','Entdecke {name}. Prüfe vor der Nutzung die Quelle und Bewertungshinweise.','Explorez {name}. Vérifiez la source et les notes avant utilisation.','Jelajahi {name}. Periksa sumber dan catatan tinjauan sebelum digunakan.'],
} satisfies Record<string, readonly string[]>

const titles: Record<RankingKind, readonly string[]> = {
  'highest-quality': ['Highest quality','高质量技能','高品質スキル','고품질 스킬','Skills de mayor calidad','Hochwertige Skills','Skills de qualité','Skill berkualitas'],
  'most-starred': ['GitHub stars','GitHub 人气榜','GitHub スターランキング','GitHub 스타 순위','Estrellas de GitHub','GitHub-Sterne','Étoiles GitHub','Bintang GitHub'],
  'recently-updated': ['Recently updated','最近更新','最近の更新','최근 업데이트','Actualizaciones recientes','Zuletzt aktualisiert','Mises à jour récentes','Baru diperbarui'],
  'new-this-week': ['New this week','本周新增技能','今週の新着スキル','이번 주 신규 스킬','Nuevos skills esta semana','Neue Skills dieser Woche','Nouveaux skills cette semaine','Skill baru minggu ini'],
  'agent-usage': ['Agent outcomes','Agent 使用证据','Agent 利用の証拠','Agent 사용 근거','Evidencia de uso por agentes','Agent-Nutzungsbelege','Preuves d’utilisation agent','Bukti penggunaan agent'],
  'success-rate': ['Success rate','结果成功率','結果の成功率','결과 성공률','Tasa de éxito','Erfolgsrate','Taux de réussite','Tingkat keberhasilan'],
  'safe-auto-install': ['Install readiness','安装准备度','インストール準備度','설치 준비도','Preparación de instalación','Installationsbereitschaft','Préparation à l’installation','Kesiapan instalasi'],
  'agent-platform': ['{name} skills','{name} 技能','{name} スキル','{name} 스킬','Skills para {name}','Skills für {name}','Skills pour {name}','Skill untuk {name}'],
  'use-case': ['{name} skills','{name} 技能','{name} スキル','{name} 스킬','Skills de {name}','Skills für {name}','Skills pour {name}','Skill untuk {name}'],
}

const methods: Record<RankingKind, readonly string[]> = {
  'most-starred': ['Ordered by repository star count, with each GitHub project listed once.','按仓库 Star 数排序，同一 GitHub 项目只出现一次。','スター数順。同じGitHubプロジェクトは1回だけ掲載します。','저장소 스타 수순이며 GitHub 프로젝트는 한 번만 표시됩니다.','Por estrellas del repositorio, con cada proyecto una sola vez.','Nach Repository-Sternen; jedes GitHub-Projekt erscheint einmal.','Par étoiles du dépôt, chaque projet n’apparaît qu’une fois.','Menurut bintang repositori; setiap proyek hanya tampil sekali.'],
  'new-this-week': ['Only skills indexed within the last seven days, newest first. This is the registry addition date, not the repository creation date.','仅展示最近 7 天收录的技能，按收录时间从新到旧排列。这是本站收录日期，不是仓库创建日期。','過去7日間の登録を新しい順に表示。リポジトリ作成日ではなく登録日です。','최근 7일 등록된 스킬을 최신순으로 표시합니다. 저장소 생성일이 아닌 등록일입니다.','Solo indexados en los últimos siete días, más recientes primero. No es la fecha de creación del repositorio.','Nur in den letzten sieben Tagen indexierte Skills, neueste zuerst. Gemeint ist das Indexierungsdatum, nicht die Repository-Erstellung.','Uniquement les skills indexés ces sept derniers jours, du plus récent au plus ancien. Ce n’est pas la date de création du dépôt.','Hanya skill yang diindeks tujuh hari terakhir, terbaru dahulu. Ini tanggal pengindeksan, bukan pembuatan repositori.'],
  'recently-updated': ['Ordered by recorded repository activity. A registry update is used when a push date was not recorded; the row identifies which date is shown.','按已记录的仓库活跃时间排序。没有仓库推送日期时会采用目录更新时间，列表会明确区分日期来源。','記録された更新順。push日がない場合は登録情報の更新日を使い、行に出典を表示します。','기록된 저장소 활동순입니다. 푸시 날짜가 없으면 디렉터리 갱신일을 사용하고 출처를 표시합니다.','Por actividad registrada. Sin fecha de push se usa la actualización del directorio, identificada en la fila.','Nach erfasster Aktivität. Fehlt das Push-Datum, wird das gekennzeichnete Verzeichnisdatum verwendet.','Par activité enregistrée. Sans date de push, la date du répertoire est utilisée et indiquée.','Menurut aktivitas tercatat. Jika tanggal push tidak ada, tanggal pembaruan direktori dipakai dan ditandai.'],
  'highest-quality': ['Combines quality, freshness, installation metadata and outcome evidence, with a relevance penalty for records that are not Skill-like.','综合质量、新鲜度、安装元数据与结果证据，并降低非 Skill 类记录的排名。','品質、鮮度、インストール情報、結果証拠を組み合わせ、Skillらしくない記録を減点します。','품질, 최신성, 설치 정보, 결과 근거를 결합하며 Skill 관련성이 낮은 항목은 감점합니다.','Combina calidad, actualidad, instalación y resultados; penaliza registros poco relacionados con skills.','Kombiniert Qualität, Aktualität, Installationsdaten und Ergebnisse; Skill-ferne Einträge werden abgewertet.','Combine qualité, actualité, installation et résultats, avec pénalité pour les entrées peu liées aux skills.','Menggabungkan kualitas, kebaruan, metadata instalasi dan hasil; entri yang kurang mirip Skill diberi penalti.'],
  'agent-usage': ['Requires reported outcomes; combines outcome signals, evidence confidence and usage volume. Reports are not independent safety certification.','需要实际报告的结果，综合结果信号、证据置信度和使用量；这些报告不构成独立安全认证。','報告済み結果が必要です。結果、証拠の確かさ、利用量を組み合わせます。独立した安全認証ではありません。','보고된 결과가 필요합니다. 결과 신호, 근거 신뢰도, 사용량을 결합하며 독립 안전 인증은 아닙니다.','Requiere resultados reportados; combina señales, confianza y volumen. No es certificación de seguridad independiente.','Erfordert gemeldete Ergebnisse; kombiniert Signale, Konfidenz und Nutzung. Keine unabhängige Sicherheitszertifizierung.','Exige des résultats rapportés ; combine signaux, confiance et volume. Pas une certification de sécurité indépendante.','Memerlukan laporan hasil; menggabungkan sinyal, keyakinan dan penggunaan. Bukan sertifikasi keamanan independen.'],
  'success-rate': ['Requires outcome reports with a known success rate. Ranking also considers evidence confidence and agent outcome signals, not success rate alone.','需要有已知成功率的结果报告；同时考虑证据置信度与 Agent 结果信号，不仅按成功率排序。','成功率が分かる結果報告が必要です。成功率だけでなく、証拠の確かさと結果指標も考慮します。','성공률이 알려진 결과 보고가 필요합니다. 성공률 외에 근거 신뢰도와 결과 신호도 고려합니다.','Requiere resultados con tasa conocida; también considera confianza y señales, no solo la tasa.','Erfordert Ergebnisse mit bekannter Erfolgsrate; berücksichtigt zusätzlich Konfidenz und Ergebnissignale.','Exige un taux connu ; prend aussi en compte la confiance et les signaux, pas seulement le taux.','Memerlukan hasil dengan tingkat sukses diketahui; mempertimbangkan keyakinan dan sinyal, bukan hanya tingkat sukses.'],
  'safe-auto-install': ['Combines installation metadata and outcome evidence, accounting for reported risk and setup friction. It does not authorize automatic installation.','综合安装元数据和结果证据，考虑已报告的风险与配置阻力；此榜单不等于允许自动安装。','インストール情報、結果証拠、リスクや設定の手間を考慮します。自動インストールを許可するものではありません。','설치 정보와 결과 근거, 보고된 위험과 설정 부담을 고려합니다. 자동 설치를 허가하지 않습니다.','Combina instalación y resultados, considerando riesgos y configuración. No autoriza la instalación automática.','Kombiniert Installationsdaten und Ergebnisse, einschließlich Risiken und Einrichtungsaufwand. Keine Freigabe zur automatischen Installation.','Combine installation et résultats en tenant compte des risques et de la configuration. N’autorise pas l’installation automatique.','Menggabungkan metadata instalasi dan hasil, memperhitungkan risiko serta pengaturan. Tidak mengizinkan instalasi otomatis.'],
  'agent-platform': ['Uses explicit platform mentions or inferred task fit, plus quality and outcome evidence. Inferred compatibility is not a runtime test.','根据明确的平台提及或推断的任务适配，再结合质量和结果证据排序；推断兼容不代表运行测试通过。','明示されたプラットフォーム、推定タスク適合度、品質と結果証拠を使います。推定互換性は動作テストではありません。','플랫폼 명시 또는 추론한 작업 적합성에 품질과 결과 근거를 결합합니다. 추론한 호환성은 실행 테스트가 아닙니다.','Usa menciones de plataforma o ajuste inferido, calidad y resultados. Compatibilidad inferida no es una prueba de ejecución.','Nutzt Plattformnennungen oder abgeleitete Aufgabenpassung, Qualität und Ergebnisse. Abgeleitete Kompatibilität ist kein Laufzeittest.','Utilise les mentions de plateforme ou l’adéquation déduite, la qualité et les résultats. La compatibilité déduite n’est pas un test d’exécution.','Memakai penyebutan platform atau kecocokan tugas tersirat, kualitas dan hasil. Kompatibilitas tersirat bukan uji eksekusi.'],
  'use-case': ['Matches task and source metadata, then considers quality, popularity and freshness. Source descriptions are not execution evidence.','先匹配任务与来源元数据，再考虑质量、人气和新鲜度；来源描述不是执行证据。','タスクとソース情報を照合し、品質、人気、鮮度を考慮します。説明文は実行の証拠ではありません。','작업과 출처 정보를 매칭한 뒤 품질, 인기도, 최신성을 고려합니다. 설명은 실행 근거가 아닙니다.','Relaciona tareas y metadatos, luego calidad, popularidad y actualidad. Las descripciones no prueban ejecución.','Gleicht Aufgaben und Metadaten ab, dann Qualität, Popularität und Aktualität. Beschreibungen sind keine Ausführungsbelege.','Associe tâches et métadonnées, puis qualité, popularité et actualité. Les descriptions ne prouvent pas l’exécution.','Mencocokkan tugas dan metadata, lalu kualitas, popularitas dan kebaruan. Deskripsi bukan bukti eksekusi.'],
}

export function rankingCopy(locale: Locale) {
  const index = locales.indexOf(locale)
  return Object.fromEntries(Object.entries(labels).map(([key, values]) => [key, values[index]])) as Record<keyof typeof labels, string>
}
const taskNames: Record<string, readonly string[]> = {
  'web-scraping': ['网页抓取','Web スクレイピング','웹 스크래핑','Extracción web','Web-Scraping','Extraction web','Scraping web'],
  'coding-agents': ['编程 Agent','コーディング Agent','코딩 Agent','Agentes de programación','Coding-Agents','Agents de programmation','Agent pemrograman'],
  'rag-knowledge': ['RAG 与知识库','RAG とナレッジ','RAG 및 지식','RAG y conocimiento','RAG und Wissen','RAG et connaissances','RAG dan pengetahuan'],
  'browser-automation': ['浏览器自动化','ブラウザー自動化','브라우저 자동화','Automatización del navegador','Browser-Automatisierung','Automatisation du navigateur','Otomasi browser'],
  'research-agents': ['研究 Agent','リサーチ Agent','리서치 Agent','Agentes de investigación','Recherche-Agents','Agents de recherche','Agent riset'],
  'workflow-automation': ['工作流自动化','ワークフロー自動化','워크플로 자동화','Automatización de flujos','Workflow-Automatisierung','Automatisation des workflows','Otomasi alur kerja'],
  'document-processing': ['文档处理','文書処理','문서 처리','Procesamiento de documentos','Dokumentverarbeitung','Traitement de documents','Pemrosesan dokumen'],
  'data-analysis': ['数据分析','データ分析','데이터 분석','Análisis de datos','Datenanalyse','Analyse de données','Analisis data'],
  'finance-quant': ['金融与量化','金融・クオンツ','금융 및 퀀트','Finanzas y análisis cuantitativo','Finanzen und Quant','Finance et quantitatif','Keuangan dan kuantitatif'],
  'sports-analytics': ['体育分析','スポーツ分析','스포츠 분석','Análisis deportivo','Sportanalyse','Analyse sportive','Analisis olahraga'],
  'github-automation': ['GitHub 自动化','GitHub 自動化','GitHub 자동화','Automatización de GitHub','GitHub-Automatisierung','Automatisation GitHub','Otomasi GitHub'],
  'testing-qa': ['测试与质量保障','テスト・品質保証','테스트 및 품질 보증','Pruebas y calidad','Tests und Qualitätssicherung','Tests et assurance qualité','Pengujian dan jaminan kualitas'],
  'content-automation': ['内容自动化','コンテンツ自動化','콘텐츠 자동화','Automatización de contenido','Content-Automatisierung','Automatisation de contenu','Otomasi konten'],
  'marketing-growth': ['营销与增长','マーケティング・成長','마케팅 및 성장','Marketing y crecimiento','Marketing und Wachstum','Marketing et croissance','Pemasaran dan pertumbuhan'],
  'design-creative': ['设计与创意','デザイン・創作','디자인 및 창작','Diseño y creatividad','Design und Kreativität','Design et création','Desain dan kreativitas'],
  'video-creation': ['视频创作','動画制作','영상 제작','Creación de vídeo','Videoerstellung','Création vidéo','Pembuatan video'],
  'presentation-generation': ['演示文稿','プレゼンテーション','프레젠테이션','Presentaciones','Präsentationen','Présentations','Presentasi'],
  'security-compliance': ['安全与合规','セキュリティ・コンプライアンス','보안 및 규정 준수','Seguridad y cumplimiento','Sicherheit und Compliance','Sécurité et conformité','Keamanan dan kepatuhan'],
  'legal-compliance': ['法律与合规','法務・コンプライアンス','법률 및 규정 준수','Legal y cumplimiento','Recht und Compliance','Droit et conformité','Hukum dan kepatuhan'],
  'education-tutoring': ['教育与辅导','教育・指導','교육 및 지도','Educación y tutoría','Bildung und Nachhilfe','Éducation et tutorat','Pendidikan dan bimbingan'],
  'database-sql': ['数据库与 SQL','データベース・SQL','데이터베이스 및 SQL','Bases de datos y SQL','Datenbanken und SQL','Bases de données et SQL','Basis data dan SQL'],
  'multimodal-media': ['多模态媒体','マルチモーダルメディア','멀티모달 미디어','Medios multimodales','Multimodale Medien','Médias multimodaux','Media multimodal'],
  'customer-support': ['客户支持','カスタマーサポート','고객 지원','Atención al cliente','Kundensupport','Service client','Dukungan pelanggan'],
  'sales-crm': ['销售与 CRM','営業・CRM','영업 및 CRM','Ventas y CRM','Vertrieb und CRM','Ventes et CRM','Penjualan dan CRM'],
  'email-calendar': ['邮件与日历','メール・カレンダー','이메일 및 일정','Correo y calendario','E-Mail und Kalender','E-mail et calendrier','Email dan kalender'],
  'local-desktop': ['本地桌面','ローカルデスクトップ','로컬 데스크톱','Escritorio local','Lokaler Desktop','Bureau local','Desktop lokal'],
}
export function localizedRanking(ranking: RankingDefinition, locale: Locale) {
  const index = locales.indexOf(locale)
  const name = ranking.kind === 'agent-platform' ? ranking.shortTitle : locale !== 'en' && ranking.useCaseSlug ? taskNames[ranking.useCaseSlug]?.[index - 1] || directoryLabel(locale, ranking.useCaseSlug) : ranking.shortTitle
  const label = ranking.slug === 'agent-proven' ? rankingCopy(locale).report : titles[ranking.kind][index].replace('{name}', name)
  const title = locale === 'en' ? ranking.title : label
  return { title, shortTitle: locale === 'en' ? ranking.shortTitle : label,
    description: locale === 'en' ? ranking.description : rankingCopy(locale).intro.replace('{name}', title),
    method: methods[ranking.kind][index] }
}
