import type { Locale } from '@/lib/i18n/config'

const keys = ['useAgent', 'reviewSource', 'recorded', 'unverified', 'changed', 'recordedNote', 'unverifiedNote', 'changedNote', 'sourceTrust', 'agentAccess', 'registryUpdated', 'sourcePath', 'costNote', 'compatibilityNote', 'creatorTools', 'workflow', 'stepOne', 'stepTwo', 'stepThree', 'signalsNote', 'copyNote', 'moreDetails', 'versionNote'] as const
export type SkillProfileCopyKey = typeof keys[number]
const copy: Record<Locale, readonly string[]> = {
  en: ['Use with my agent', 'Review the source', 'Skill source recorded', 'Source structure unverified', 'Source needs review', 'Skill instructions are recorded. This is not a runtime test, safety guarantee or compatibility certification.', 'A repository listing is not proof of an installable skill. Review its instructions before proposing any installation.', 'The tracked source changed or could not be synchronized. Review the current source before installing.', 'Source & trust', 'Agent access', 'Registry updated', 'Instruction path', 'Check the source for dependencies, API keys and third-party costs. A public repository does not mean every service is free.', 'Listed tools are metadata hints, not tested compatibility. Agent prompts are suggested handoffs.', 'For the creator', 'Start with one small task', 'Read the source. Confirm the input, expected output, dependencies and permissions.', 'Ask your agent for a plan. Approve setup and any costs before running a small isolated test.', 'Check the output and changed files. Report only what actually ran; keep the source revision for reproduction.', 'Repository metadata and review signals are advisory. Popularity, source discovery and successful execution are different facts.', 'Copies are not installs. Installation counts require a reported successful installation; they are not a blanket quality guarantee.', 'More details', 'Version reported in registry metadata; check source releases before relying on it.'],
  zh: ['给我的 Agent 使用', '查看并核实来源', '已记录技能来源', '来源结构待验证', '来源需要复核', '已记录技能指令路径，不代表本站运行测试、安全保证或兼容性认证。', '收录仓库不等于确认可安装技能。请先核实指令，再提出安装方案。', '已跟踪的来源发生变化或同步失败，请在安装前复核当前来源。', '来源与信任', 'Agent 接入', '目录更新于', '技能指令路径', '请在来源中核实依赖、API 密钥及第三方费用。公开仓库不代表所有服务免费。', '工具列表来自元数据，并非已测试的兼容性；Agent 提示词是建议的交接方式。', '创作者工具', '从一个小任务开始', '阅读来源，确认输入、预期输出、依赖和权限。', '先让 Agent 提出计划，批准环境配置和费用，再进行隔离的小规模测试。', '检查输出和变更文件，只报告实际执行结果，并保留来源版本以便复现。', '仓库元数据和审核信号仅供参考。受欢迎、已发现来源、成功运行是不同的事实。', '复制不等于安装。安装数需有成功安装回报，不代表全面的质量保证。', '更多详情', '版本来自目录元数据，使用前请核实来源发布记录。'],
  ja: ['Agent で使う', 'ソースを確認', 'スキルのソースを記録済み', 'ソース構造は未確認', 'ソースの再確認が必要', '手順のパスを記録しています。実行テスト、安全保証、互換性認証ではありません。', 'リポジトリの掲載はインストール可能なスキルの証明ではありません。まず手順を確認してください。', 'ソースが変更されたか同期に失敗しました。インストール前に確認してください。', 'ソースと信頼性', 'Agent 接続', '登録情報の更新日', '手順のパス', '依存関係、API キー、外部サービスの料金をソースで確認してください。公開リポジトリでも全サービスが無料とは限りません。', 'ツール一覧はメタデータであり、互換性のテスト結果ではありません。プロンプトは提案です。', 'クリエイター向け', '小さなタスクから始める', 'ソースを読み、入力、出力、依存関係、権限を確認します。', 'Agent に計画を求め、設定と費用を承認してから隔離環境でテストします。', '出力と変更ファイルを確認し、実行した結果だけを報告します。再現用にソースの版を保存します。', 'メタデータと審査情報は参考です。人気、ソースの発見、実行成功は別の事実です。', 'コピーはインストールではありません。件数は成功報告に基づき、品質全体を保証しません。', '詳細情報', '登録されたバージョンです。ソースのリリース情報を確認してください。'],
  ko: ['Agent로 사용', '소스 확인', '스킬 소스 기록됨', '소스 구조 미확인', '소스 재검토 필요', '지침 경로가 기록되어 있습니다. 실행 테스트, 안전 보장 또는 호환성 인증은 아닙니다.', '저장소 등록은 설치 가능한 스킬의 증거가 아닙니다. 설치를 제안하기 전에 지침을 확인하세요.', '소스가 변경되었거나 동기화에 실패했습니다. 설치 전에 현재 소스를 확인하세요.', '소스 및 신뢰', 'Agent 연결', '목록 업데이트', '지침 경로', '소스에서 의존성, API 키 및 외부 서비스 비용을 확인하세요. 공개 저장소라고 모든 서비스가 무료는 아닙니다.', '도구 목록은 메타데이터이며 테스트된 호환성이 아닙니다. 프롬프트는 제안입니다.', '제작자 도구', '작은 작업부터 시작', '소스를 읽고 입력, 출력, 의존성 및 권한을 확인하세요.', 'Agent에게 계획을 요청하고 설정과 비용을 승인한 뒤 격리 환경에서 테스트하세요.', '출력과 변경 파일을 확인하고 실제 실행 결과만 보고하세요. 재현을 위해 소스 버전을 보관하세요.', '메타데이터와 검토 신호는 참고용입니다. 인기, 소스 발견, 실행 성공은 서로 다른 사실입니다.', '복사는 설치가 아닙니다. 설치 수는 성공 보고에 기반하며 전체 품질을 보장하지 않습니다.', '추가 정보', '목록에 보고된 버전입니다. 소스 릴리스를 확인하세요.'],
  es: ['Usar con mi agente', 'Revisar el código fuente', 'Fuente del skill registrada', 'Estructura sin verificar', 'La fuente requiere revisión', 'La ruta de instrucciones está registrada. No implica pruebas de ejecución, seguridad ni compatibilidad.', 'Publicar un repositorio no demuestra que sea un skill instalable. Revisa las instrucciones antes de proponer una instalación.', 'La fuente cambió o no pudo sincronizarse. Revísala antes de instalar.', 'Fuente y confianza', 'Acceso para agentes', 'Registro actualizado', 'Ruta de instrucciones', 'Consulta dependencias, claves API y costes externos en la fuente. Un repositorio público no implica servicios gratuitos.', 'Las herramientas son indicios de metadatos, no compatibilidad probada. Los prompts son sugerencias.', 'Para el creador', 'Empieza con una tarea pequeña', 'Lee la fuente y confirma entradas, resultados, dependencias y permisos.', 'Pide un plan al agente. Aprueba la configuración y los costes antes de probar en un entorno aislado.', 'Comprueba resultados y archivos modificados. Informa solo de lo ejecutado y conserva la revisión de la fuente.', 'Los metadatos y revisiones son orientativos. Popularidad, descubrimiento y ejecución correcta son hechos distintos.', 'Copiar no es instalar. Los recuentos requieren un informe de instalación correcta, no garantizan calidad general.', 'Más detalles', 'Versión declarada en el registro; consulta las versiones de la fuente.'],
  de: ['Mit meinem Agent nutzen', 'Quelle prüfen', 'Skill-Quelle erfasst', 'Quellstruktur ungeprüft', 'Quelle erneut prüfen', 'Ein Anleitungspfad ist erfasst. Das ist kein Ausführungstest und keine Sicherheits- oder Kompatibilitätsgarantie.', 'Ein gelistetes Repository beweist keinen installierbaren Skill. Prüfe zuerst die Anleitungen.', 'Die Quelle wurde geändert oder konnte nicht synchronisiert werden. Vor der Installation prüfen.', 'Quelle und Vertrauen', 'Agent-Zugang', 'Verzeichnis aktualisiert', 'Anleitungspfad', 'Prüfe Abhängigkeiten, API-Schlüssel und externe Kosten in der Quelle. Öffentliche Repositories bedeuten nicht, dass alle Dienste kostenlos sind.', 'Tools sind Metadatenhinweise, keine getestete Kompatibilität. Prompts sind Vorschläge.', 'Für Ersteller', 'Mit einer kleinen Aufgabe beginnen', 'Quelle lesen und Eingaben, Ergebnisse, Abhängigkeiten sowie Berechtigungen prüfen.', 'Agent um einen Plan bitten. Einrichtung und Kosten vor einem isolierten Test genehmigen.', 'Ergebnisse und geänderte Dateien prüfen. Nur tatsächliche Ausführungen melden und die Quellrevision aufbewahren.', 'Metadaten und Prüfungen dienen der Orientierung. Beliebtheit, Quellenerfassung und erfolgreiche Ausführung sind verschiedene Fakten.', 'Kopieren ist keine Installation. Zahlen benötigen eine Erfolgsmeldung und garantieren keine allgemeine Qualität.', 'Weitere Details', 'Version aus den Verzeichnismetadaten; Releases der Quelle prüfen.'],
  fr: ['Utiliser avec mon agent', 'Examiner la source', 'Source du skill enregistrée', 'Structure non vérifiée', 'Source à réexaminer', 'Un chemin vers les instructions est enregistré. Cela ne constitue pas un test, une garantie de sécurité ou de compatibilité.', 'Un dépôt répertorié ne prouve pas qu’un skill est installable. Vérifiez les instructions avant de proposer une installation.', 'La source a changé ou sa synchronisation a échoué. Vérifiez-la avant installation.', 'Source et confiance', 'Accès agent', 'Registre mis à jour', 'Chemin des instructions', 'Vérifiez les dépendances, clés API et frais externes dans la source. Un dépôt public ne rend pas tous les services gratuits.', 'Les outils sont des indications de métadonnées, pas une compatibilité testée. Les prompts sont des suggestions.', 'Pour le créateur', 'Commencer par une petite tâche', 'Lisez la source et confirmez entrées, résultats, dépendances et permissions.', 'Demandez un plan à l’agent. Approuvez la configuration et les coûts avant un test isolé.', 'Vérifiez résultats et fichiers modifiés. Signalez uniquement ce qui a été exécuté et conservez la révision source.', 'Métadonnées et examens sont indicatifs. Popularité, découverte et exécution réussie sont des faits distincts.', 'Copier ne signifie pas installer. Les compteurs nécessitent un rapport de réussite et ne garantissent pas la qualité globale.', 'Plus de détails', 'Version déclarée dans le registre ; vérifiez les versions de la source.'],
  id: ['Gunakan dengan agent saya', 'Tinjau sumber', 'Sumber skill tercatat', 'Struktur sumber belum diverifikasi', 'Sumber perlu ditinjau', 'Jalur instruksi telah dicatat. Ini bukan uji eksekusi, jaminan keamanan, atau sertifikasi kompatibilitas.', 'Repositori terdaftar bukan bukti skill dapat dipasang. Periksa instruksi sebelum mengusulkan pemasangan.', 'Sumber berubah atau gagal disinkronkan. Tinjau sumber terbaru sebelum memasang.', 'Sumber dan kepercayaan', 'Akses agent', 'Direktori diperbarui', 'Jalur instruksi', 'Periksa dependensi, kunci API, dan biaya layanan pihak ketiga pada sumber. Repositori publik tidak berarti semua layanan gratis.', 'Daftar alat adalah petunjuk metadata, bukan kompatibilitas teruji. Prompt adalah saran.', 'Untuk kreator', 'Mulai dengan tugas kecil', 'Baca sumber dan pastikan masukan, keluaran, dependensi, serta izin.', 'Minta rencana dari agent. Setujui pengaturan dan biaya sebelum uji terisolasi.', 'Periksa hasil dan berkas yang berubah. Laporkan hanya yang dijalankan dan simpan revisi sumber.', 'Metadata dan tinjauan bersifat saran. Popularitas, penemuan sumber, dan keberhasilan eksekusi adalah fakta berbeda.', 'Menyalin bukan memasang. Jumlah instalasi memerlukan laporan berhasil dan bukan jaminan kualitas menyeluruh.', 'Detail lainnya', 'Versi dilaporkan dalam metadata direktori; periksa rilis sumber.'],
}

export function skillProfileCopy(locale: Locale, key: SkillProfileCopyKey) {
  return copy[locale][keys.indexOf(key)]
}
export const skillProfileCopyKeys = keys
export const skillProfileLocales = copy
