import type { Locale } from './config'

// New intake/recovery copy is kept together so all supported languages stay aligned.
const rows = {
  support: ['Contact support', '联系支持', 'サポートに連絡', '지원 문의', 'Contactar con soporte', 'Support kontaktieren', 'Contacter le support', 'Hubungi dukungan'],
  copyError: ['Could not copy. Please try again.', '复制失败，请重试。', 'コピーできませんでした。再試行してください。', '복사하지 못했습니다. 다시 시도하세요.', 'No se pudo copiar. Inténtalo de nuevo.', 'Kopieren fehlgeschlagen. Erneut versuchen.', 'Copie impossible. Réessayez.', 'Gagal menyalin. Coba lagi.'],
  optional: ['Optional details', '选填信息', '任意の詳細', '선택 정보', 'Datos opcionales', 'Optionale Angaben', 'Informations facultatives', 'Detail opsional'],
  yourIdentity: ['Your profile (optional)', '你的账号（选填）', 'あなたのプロフィール（任意）', '내 프로필 (선택)', 'Tu perfil (opcional)', 'Dein Profil (optional)', 'Votre profil (facultatif)', 'Profil Anda (opsional)'],
  identityHint: ['These are your accounts, not the repository author. Optional links do not verify identity or ownership.', '请填写你本人的账号，不是仓库作者。选填链接不代表身份或所有权已认证。', 'リポジトリ作者ではなく、あなたのアカウントです。リンクは本人確認や所有権の証明にはなりません。', '저장소 작성자가 아닌 본인의 계정입니다. 링크는 신원이나 소유권 인증이 아닙니다.', 'Son tus cuentas, no las del autor. Los enlaces no verifican identidad ni propiedad.', 'Deine Konten, nicht die des Repository-Autors. Links bestätigen weder Identität noch Eigentum.', 'Vos comptes, pas ceux de l’auteur. Les liens ne prouvent ni identité ni propriété.', 'Akun Anda, bukan penulis repositori. Tautan tidak memverifikasi identitas atau kepemilikan.'],
  pathSearch: ['Filter by SKILL.md path', '按 SKILL.md 路径搜索', 'SKILL.md パスで絞り込む', 'SKILL.md 경로 검색', 'Filtrar por ruta SKILL.md', 'Nach SKILL.md-Pfad filtern', 'Filtrer par chemin SKILL.md', 'Filter jalur SKILL.md'],
  more: ['Load more paths', '加载更多路径', 'パスをさらに表示', '경로 더 보기', 'Cargar más rutas', 'Weitere Pfade laden', 'Charger plus de chemins', 'Muat jalur lainnya'],
  limits: ['Choose up to 5 skills. Anonymous limits: 5 submissions and 20 searches per day. Retries reuse your receipt.', '一次最多选 5 个。匿名提交限额：每天 5 次提交、20 次查找；重试复用回执。', '最大 5 件選べます。匿名利用は 1 日 5 件の投稿、20 回の検索まで。再試行は同じ受付票を使います。', '최대 5개 선택. 익명 사용은 하루 제출 5회, 검색 20회입니다. 재시도는 접수증을 재사용합니다.', 'Elige hasta 5. Límite anónimo: 5 envíos y 20 búsquedas al día. Los reintentos reutilizan el recibo.', 'Bis zu 5 Skills. Anonym: 5 Einreichungen und 20 Suchen täglich. Wiederholungen nutzen denselben Beleg.', 'Jusqu’à 5 skills. Anonyme : 5 envois et 20 recherches par jour. Les nouvelles tentatives réutilisent le reçu.', 'Pilih hingga 5 skill. Anonim: 5 kiriman dan 20 pencarian per hari. Percobaan ulang memakai tanda terima yang sama.'],
  capped: ['More paths may exist. Narrow the path filter or paste a direct SKILL.md link.', '可能还有未显示的路径。请缩小路径范围，或粘贴具体 SKILL.md 链接。', '他のパスがある可能性があります。絞り込むか SKILL.md のリンクを指定してください。', '표시되지 않은 경로가 있을 수 있습니다. 경로를 좁히거나 SKILL.md 링크를 입력하세요.', 'Puede haber más rutas. Filtra o pega un enlace directo a SKILL.md.', 'Weitere Pfade möglich. Filter eingrenzen oder direkten SKILL.md-Link einfügen.', 'D’autres chemins peuvent exister. Filtrez ou collez un lien SKILL.md direct.', 'Mungkin ada jalur lain. Persempit filter atau tempel tautan SKILL.md langsung.'],
  selection: ['Selected', '已选择', '選択済み', '선택됨', 'Seleccionados', 'Ausgewählt', 'Sélection', 'Dipilih'],
  githubError: ['Enter a GitHub username or profile URL.', '请输入 GitHub 用户名或个人主页链接。', 'GitHub ユーザー名かプロフィール URL を入力してください。', 'GitHub 사용자명 또는 프로필 URL을 입력하세요.', 'Introduce tu usuario o URL de perfil de GitHub.', 'GitHub-Benutzernamen oder Profil-URL eingeben.', 'Saisissez un identifiant ou une URL de profil GitHub.', 'Masukkan nama pengguna atau URL profil GitHub.'],
  xError: ['Enter an X username or profile URL.', '请输入 X 用户名或个人主页链接。', 'X のユーザー名かプロフィール URL を入力してください。', 'X 사용자명 또는 프로필 URL을 입력하세요.', 'Introduce tu usuario o URL de perfil de X.', 'X-Benutzernamen oder Profil-URL eingeben.', 'Saisissez un identifiant ou une URL de profil X.', 'Masukkan nama pengguna atau URL profil X.'],
  tagsError: ['Use at most 10 tags, up to 40 characters each.', '最多 10 个标签，每个不超过 40 字符。', 'タグは 10 個、各 40 文字までです。', '태그는 최대 10개, 각 40자입니다.', 'Máximo 10 etiquetas de 40 caracteres.', 'Maximal 10 Tags mit je 40 Zeichen.', '10 tags maximum, 40 caractères chacun.', 'Maksimal 10 tag, masing-masing 40 karakter.'],
  retry: ['Refresh status', '刷新进度', '状態を更新', '상태 새로고침', 'Actualizar estado', 'Status aktualisieren', 'Actualiser le statut', 'Perbarui status'],
  receipt: ['Submission receipt', '提交回执', '投稿受付票', '제출 접수증', 'Recibo de envío', 'Einreichungsbeleg', 'Reçu de soumission', 'Tanda terima kiriman'],
  saved: ['Your skill is submitted.', '恭喜，Skill 已提交！', 'スキルを受け付けました。', '스킬이 제출되었습니다.', 'Tu skill se ha enviado.', 'Dein Skill wurde eingereicht.', 'Votre skill a été soumise.', 'Skill Anda telah dikirim.'],
  pending: ['Saved for review. Submission is not publication or a safety certification.', '已保存，等待审核。提交成功不代表已发布，也不是安全认证。', '審査待ちとして保存しました。公開や安全性の認証ではありません。', '심사 대기로 저장되었습니다. 공개 또는 안전 인증을 뜻하지 않습니다.', 'Guardada para revisión. No significa publicación ni certificación de seguridad.', 'Zur Prüfung gespeichert. Keine Veröffentlichung oder Sicherheitszertifizierung.', 'Enregistrée pour examen. Ce n’est ni une publication ni une certification de sécurité.', 'Disimpan untuk ditinjau. Bukan publikasi atau sertifikasi keamanan.'],
  published: ['Your skill is now public.', 'Skill 已公开收录', 'スキルが公開されました。', '스킬이 공개되었습니다.', 'Tu skill ya es pública.', 'Dein Skill ist jetzt öffentlich.', 'Votre skill est maintenant publique.', 'Skill Anda kini publik.'],
  static: ['Static checks passed · Not AI reviewed', '静态检查通过 · 非 AI 审核', '静的検査済み・AI 審査なし', '정적 검사 통과 · AI 심사 아님', 'Comprobaciones estáticas · Sin revisión IA', 'Statisch geprüft · Nicht KI-geprüft', 'Vérifications statiques · Sans examen IA', 'Pemeriksaan statis lulus · Bukan tinjauan AI'],
  manual: ['Human review needed', '需要人工审核', '人による審査が必要', '사람의 심사 필요', 'Requiere revisión humana', 'Manuelle Prüfung erforderlich', 'Examen humain nécessaire', 'Perlu tinjauan manusia'],
  delayed: ['Processing is taking longer. Your submission is saved; do not submit it again. Refresh later or contact support with the receipt ID.', '处理时间较长，但提交已保存，无需重复提交。稍后刷新，或向支持提供回执编号。', '処理に時間がかかっています。保存済みなので再投稿は不要です。後で更新するか受付番号を添えてお問い合わせください。', '처리가 지연되고 있습니다. 저장되었으니 다시 제출하지 마세요. 나중에 새로고침하거나 접수 ID로 문의하세요.', 'El proceso tarda más. Tu envío está guardado; no lo repitas. Actualiza después o contacta con soporte con el ID.', 'Die Verarbeitung dauert länger. Gespeichert – nicht erneut einreichen. Später aktualisieren oder Support mit Beleg-ID kontaktieren.', 'Le traitement est plus long. Votre envoi est enregistré ; ne le renvoyez pas. Actualisez plus tard ou contactez le support avec l’ID.', 'Proses lebih lama. Kiriman tersimpan; jangan kirim ulang. Perbarui nanti atau hubungi dukungan dengan ID.'],
  statusError: ['Status is temporarily unavailable. Your saved receipt is safe; try refreshing.', '暂时无法读取进度。回执仍已保存，请刷新重试。', '状態を取得できません。受付票は保存済みです。更新してください。', '상태를 불러올 수 없습니다. 접수증은 저장되었습니다. 새로고침하세요.', 'Estado no disponible. Tu recibo está guardado; actualiza.', 'Status vorübergehend nicht verfügbar. Beleg gespeichert; bitte aktualisieren.', 'Statut indisponible. Votre reçu est enregistré ; actualisez.', 'Status sementara tidak tersedia. Tanda terima tersimpan; perbarui.'],
  share: ['Share on X', '分享到 X', 'X でシェア', 'X에 공유', 'Compartir en X', 'Auf X teilen', 'Partager sur X', 'Bagikan di X'],
  copy: ['Copy share text', '复制分享文案', '共有文をコピー', '공유 문구 복사', 'Copiar texto', 'Text kopieren', 'Copier le texte', 'Salin teks'],
  copied: ['Copied', '已复制', 'コピー済み', '복사됨', 'Copiado', 'Kopiert', 'Copié', 'Disalin'],
  privateLink: ['Copy private tracking link', '复制私密进度链接', '非公開の追跡リンクをコピー', '비공개 진행 링크 복사', 'Copiar enlace privado', 'Privaten Statuslink kopieren', 'Copier le lien privé', 'Salin tautan pelacakan privat'],
  privateHint: ['Keep your tracking link private. Share buttons never include this link or your receipt token.', '请妥善保存私密进度链接。分享按钮不会包含该链接或回执密钥。', '追跡リンクは非公開で保管してください。共有ボタンにはリンクやトークンを含めません。', '진행 링크는 비공개로 보관하세요. 공유 버튼에 링크나 토큰은 포함되지 않습니다.', 'Guarda el enlace en privado. Los botones de compartir no incluyen el enlace ni el token.', 'Statuslink privat aufbewahren. Teilen enthält weder diesen Link noch den Beleg-Token.', 'Gardez le lien privé. Le partage n’inclut ni ce lien ni le jeton.', 'Simpan tautan secara privat. Tombol berbagi tidak menyertakan tautan atau token.'],
  continue: ['View submission', '查看提交进度', '投稿を確認', '제출 보기', 'Ver envío', 'Einreichung ansehen', 'Voir la soumission', 'Lihat kiriman'],
  recent: ['Your recent submissions on this device', '本设备的最近提交', 'この端末の最近の投稿', '이 기기의 최근 제출', 'Envíos recientes en este dispositivo', 'Letzte Einreichungen auf diesem Gerät', 'Envois récents sur cet appareil', 'Kiriman terbaru di perangkat ini'],
  close: ['Close', '关闭', '閉じる', '닫기', 'Cerrar', 'Schließen', 'Fermer', 'Tutup'],
  failed: ['Could not confirm submission. Check the fields and retry. Saved items reuse the same receipt.', '暂时无法确认提交结果。请检查字段后重试，已保存的条目会复用同一回执。', '投稿結果を確認できません。入力を確認して再試行してください。保存済みの項目は同じ受付票を使います。', '제출 결과를 확인하지 못했습니다. 입력을 확인하고 재시도하세요. 저장된 항목은 같은 접수증을 사용합니다.', 'No se pudo confirmar el envío. Revisa y reintenta. Los elementos guardados reutilizan el recibo.', 'Einreichung nicht bestätigt. Angaben prüfen und erneut versuchen. Gespeicherte Einträge nutzen denselben Beleg.', 'Envoi non confirmé. Vérifiez puis réessayez. Les éléments enregistrés réutilisent le même reçu.', 'Hasil kiriman belum dapat dikonfirmasi. Periksa lalu coba lagi. Item tersimpan memakai tanda terima yang sama.'],
  rate: ['Daily limit reached. Keep your draft and try again tomorrow.', '已达每日限额。草稿已保留，请明天再试。', '1 日の上限です。下書きを保存して明日再試行してください。', '일일 한도에 도달했습니다. 초안을 유지하고 내일 다시 시도하세요.', 'Límite diario alcanzado. Conserva el borrador y vuelve mañana.', 'Tageslimit erreicht. Entwurf behalten und morgen erneut versuchen.', 'Limite quotidienne atteinte. Gardez le brouillon et réessayez demain.', 'Batas harian tercapai. Simpan draf dan coba besok.'],
} as const

export function submissionFlowCopy(locale: Locale, key: keyof typeof rows) {
  const index = ['en', 'zh', 'ja', 'ko', 'es', 'de', 'fr', 'id'].indexOf(locale)
  return rows[key][index < 0 ? 0 : index]
}
