import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!
const supabase = createClient(supabaseUrl, supabaseKey)

const popularSkills = [
  {
    slug: 'find-skills',
    name: 'Find Skills',
    description: 'Helps AI agents discover and recommend relevant skills from the marketplace',
    long_description: 'This skill enables AI agents to search through available skills, understand their capabilities, and recommend the most suitable ones based on user needs. Perfect for agents that need to dynamically discover tools.',
    tagline: 'Discover the right skill for any task',
    author_name: 'skills-community',
    repository: 'https://github.com/skills/find-skills',
    github_repo: 'skills/find-skills',
    github_stars: 245,
    github_forks: 32,
    category: 'productivity',
    tags: ['search', 'discovery', 'ai-agent'],
    frameworks: ['Claude', 'GPT-4', 'Cursor'],
    version: '1.2.0',
    license: 'MIT',
    install_command: 'npx skills add skills/find-skills',
    verified: true,
    submission_source: 'api',
    ai_review_approved: true,
    downloads: 1250,
    used_by: 456,
    rating: 4.8,
  },
  {
    slug: 'vercel-react-best-practices',
    name: 'Vercel React Best Practices',
    description: 'Code review assistant focused on React and Next.js best practices',
    long_description: 'Automatically reviews React and Next.js code for common issues, performance problems, and suggests improvements based on Vercel best practices.',
    tagline: 'Write better React code with AI guidance',
    author_name: 'vercel',
    repository: 'https://github.com/vercel/react-best-practices',
    github_repo: 'vercel/react-best-practices',
    github_stars: 892,
    github_forks: 124,
    category: 'code-review',
    tags: ['react', 'nextjs', 'code-quality'],
    frameworks: ['Cursor', 'Windsurf', 'Copilot'],
    version: '2.1.0',
    license: 'MIT',
    install_command: 'npx skills add vercel/react-best-practices',
    verified: true,
    submission_source: 'api',
    ai_review_approved: true,
    downloads: 3420,
    used_by: 1234,
    rating: 4.9,
  },
  {
    slug: 'web-design-guidelines',
    name: 'Web Design Guidelines',
    description: 'Provides design system recommendations and UI/UX best practices',
    long_description: 'This skill helps agents create beautiful, accessible web designs by following established design principles and modern UI patterns.',
    tagline: 'Build stunning interfaces with AI assistance',
    author_name: 'design-systems',
    repository: 'https://github.com/design-systems/guidelines',
    github_repo: 'design-systems/guidelines',
    github_stars: 567,
    github_forks: 89,
    category: 'design',
    tags: ['ui', 'ux', 'design-systems'],
    frameworks: ['Claude', 'v0', 'Cursor'],
    version: '1.5.2',
    license: 'MIT',
    install_command: 'npx skills add design-systems/guidelines',
    verified: true,
    submission_source: 'api',
    ai_review_approved: true,
    downloads: 2100,
    used_by: 789,
    rating: 4.7,
  },
  {
    slug: 'git-commit-helper',
    name: 'Git Commit Helper',
    description: 'Generates meaningful commit messages following conventional commit standards',
    long_description: 'Analyzes code changes and automatically generates clear, descriptive commit messages that follow best practices.',
    tagline: 'Never write a bad commit message again',
    author_name: 'dev-tools',
    repository: 'https://github.com/dev-tools/git-commit-helper',
    github_repo: 'dev-tools/git-commit-helper',
    github_stars: 1234,
    github_forks: 156,
    category: 'developer-tools',
    tags: ['git', 'version-control', 'productivity'],
    frameworks: ['Cursor', 'Cline', 'Windsurf'],
    version: '1.8.0',
    license: 'MIT',
    install_command: 'npx skills add dev-tools/git-commit-helper',
    verified: true,
    submission_source: 'api',
    ai_review_approved: true,
    downloads: 4500,
    used_by: 2100,
    rating: 4.8,
  },
  {
    slug: 'api-documentation-generator',
    name: 'API Documentation Generator',
    description: 'Automatically generates comprehensive API documentation from code',
    long_description: 'Scans your codebase and creates detailed, interactive API documentation with examples and usage guides.',
    tagline: 'Beautiful docs without the manual work',
    author_name: 'docs-ai',
    repository: 'https://github.com/docs-ai/api-docs-gen',
    github_repo: 'docs-ai/api-docs-gen',
    github_stars: 678,
    github_forks: 92,
    category: 'documentation',
    tags: ['api', 'docs', 'automation'],
    frameworks: ['GPT-4', 'Claude', 'Cursor'],
    version: '2.0.1',
    license: 'Apache-2.0',
    install_command: 'npx skills add docs-ai/api-docs-gen',
    verified: true,
    submission_source: 'api',
    ai_review_approved: true,
    downloads: 1890,
    used_by: 567,
    rating: 4.6,
  },
  {
    slug: 'sql-query-optimizer',
    name: 'SQL Query Optimizer',
    description: 'Analyzes and optimizes database queries for better performance',
    long_description: 'Identifies slow queries, suggests indexes, and rewrites SQL for optimal performance across PostgreSQL, MySQL, and other databases.',
    tagline: 'Make your database queries lightning fast',
    author_name: 'db-experts',
    repository: 'https://github.com/db-experts/sql-optimizer',
    github_repo: 'db-experts/sql-optimizer',
    github_stars: 445,
    github_forks: 67,
    category: 'database',
    tags: ['sql', 'optimization', 'performance'],
    frameworks: ['OpenClaw', 'Claude', 'GPT-4'],
    version: '1.4.3',
    license: 'MIT',
    install_command: 'npx skills add db-experts/sql-optimizer',
    verified: true,
    submission_source: 'api',
    ai_review_approved: true,
    downloads: 1567,
    used_by: 432,
    rating: 4.7,
  },
  {
    slug: 'test-case-generator',
    name: 'Test Case Generator',
    description: 'Automatically generates comprehensive unit and integration tests',
    long_description: 'Creates thorough test suites for your code, including edge cases and error scenarios, supporting Jest, Vitest, and more.',
    tagline: 'Achieve 100% test coverage effortlessly',
    author_name: 'testing-tools',
    repository: 'https://github.com/testing-tools/test-gen',
    github_repo: 'testing-tools/test-gen',
    github_stars: 789,
    github_forks: 103,
    category: 'testing',
    tags: ['testing', 'unit-tests', 'quality-assurance'],
    frameworks: ['Cursor', 'Copilot', 'Cline'],
    version: '1.6.0',
    license: 'MIT',
    install_command: 'npx skills add testing-tools/test-gen',
    verified: true,
    submission_source: 'api',
    ai_review_approved: true,
    downloads: 2890,
    used_by: 1100,
    rating: 4.8,
  },
  {
    slug: 'accessibility-checker',
    name: 'Accessibility Checker',
    description: 'Identifies and fixes web accessibility issues (WCAG compliance)',
    long_description: 'Scans your web application for accessibility problems and provides actionable fixes to ensure WCAG 2.1 AA compliance.',
    tagline: 'Build inclusive web experiences',
    author_name: 'a11y-tools',
    repository: 'https://github.com/a11y-tools/checker',
    github_repo: 'a11y-tools/checker',
    github_stars: 534,
    github_forks: 78,
    category: 'accessibility',
    tags: ['a11y', 'wcag', 'inclusive-design'],
    frameworks: ['v0', 'Claude', 'Cursor'],
    version: '1.3.2',
    license: 'MIT',
    install_command: 'npx skills add a11y-tools/checker',
    verified: true,
    submission_source: 'api',
    ai_review_approved: true,
    downloads: 1234,
    used_by: 456,
    rating: 4.9,
  },
  {
    slug: 'code-refactoring-assistant',
    name: 'Code Refactoring Assistant',
    description: 'Suggests and applies intelligent code refactoring improvements',
    long_description: 'Identifies code smells, duplicate code, and complexity issues, then suggests refactoring strategies to improve maintainability.',
    tagline: 'Keep your codebase clean and maintainable',
    author_name: 'refactor-ai',
    repository: 'https://github.com/refactor-ai/assistant',
    github_repo: 'refactor-ai/assistant',
    github_stars: 923,
    github_forks: 134,
    category: 'code-quality',
    tags: ['refactoring', 'clean-code', 'maintainability'],
    frameworks: ['Cursor', 'Windsurf', 'Cline'],
    version: '2.2.0',
    license: 'MIT',
    install_command: 'npx skills add refactor-ai/assistant',
    verified: true,
    submission_source: 'api',
    ai_review_approved: true,
    downloads: 3100,
    used_by: 1450,
    rating: 4.8,
  },
  {
    slug: 'security-vulnerability-scanner',
    name: 'Security Vulnerability Scanner',
    description: 'Detects security vulnerabilities and suggests fixes',
    long_description: 'Comprehensive security scanner that identifies common vulnerabilities (OWASP Top 10), dependency issues, and provides remediation guidance.',
    tagline: 'Secure your code before deployment',
    author_name: 'security-first',
    repository: 'https://github.com/security-first/scanner',
    github_repo: 'security-first/scanner',
    github_stars: 1567,
    github_forks: 234,
    category: 'security',
    tags: ['security', 'vulnerability', 'owasp'],
    frameworks: ['OpenClaw', 'Claude', 'GPT-4'],
    version: '3.1.0',
    license: 'Apache-2.0',
    install_command: 'npx skills add security-first/scanner',
    verified: true,
    submission_source: 'api',
    ai_review_approved: true,
    downloads: 5670,
    used_by: 2340,
    rating: 4.9,
  },
]

async function seedSkills() {
  console.log('🌱 开始添加热门技能到数据库...')

  for (const skill of popularSkills) {
    try {
      const { data, error } = await supabase
        .from('skills')
        .insert([skill])
        .select()
        .single()

      if (error) {
        if (error.code === '23505') {
          console.log(`⏭️  技能已存在: ${skill.name}`)
        } else {
          console.error(`❌ 添加失败 ${skill.name}:`, error.message)
        }
      } else {
        console.log(`✅ 成功添加: ${skill.name}`)
      }
    } catch (err: any) {
      console.error(`❌ 错误 ${skill.name}:`, err.message)
    }
  }

  console.log('✨ 完成！所有热门技能已添加。')
}

seedSkills()
