create table if not exists public.ranking_snapshots (
  id bigint generated by default as identity primary key,
  ranking_slug text not null,
  snapshot_date date not null default ((now() at time zone 'utc')::date),
  generated_at timestamptz not null default now(),
  methodology_version text not null,
  item_count integer not null default 0 check (item_count >= 0),
  items jsonb not null default '[]'::jsonb check (jsonb_typeof(items) = 'array'),
  source_counts jsonb not null default '{}'::jsonb check (jsonb_typeof(source_counts) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ranking_snapshots_slug_date_key unique (ranking_slug, snapshot_date)
);

comment on table public.ranking_snapshots is
  'Daily, immutable-by-date leaderboard payloads generated by the authenticated Vercel ranking cron.';

create index if not exists ranking_snapshots_slug_generated_idx
  on public.ranking_snapshots (ranking_slug, generated_at desc);

create index if not exists ranking_snapshots_generated_idx
  on public.ranking_snapshots (generated_at desc);

alter table public.ranking_snapshots enable row level security;

revoke all on table public.ranking_snapshots from public, anon, authenticated;
grant select on table public.ranking_snapshots to anon, authenticated;
grant select, insert, update, delete on table public.ranking_snapshots to service_role;

drop policy if exists "Public can read ranking snapshots" on public.ranking_snapshots;
create policy "Public can read ranking snapshots"
  on public.ranking_snapshots
  for select
  to anon, authenticated
  using (true);

revoke all on sequence public.ranking_snapshots_id_seq from public, anon, authenticated;
grant usage, select on sequence public.ranking_snapshots_id_seq to service_role;
